### ISSUE TITLE
Update to NServiceBus v6

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.RabbitMQ#104]
Task force: @mikeminutillo @johnsimons @bording 
Relates to: Particular/PlatformDevelopment#182

This is the RabbitMQ adapter epic which incorporates the work for making the RabbitMQ adapter async/await enabled. Please see [this blog post](http://particular.net/blog/async-await-its-time) about the reasoning behind it.

- [ ]  Update samples https://github.com/Particular/docs.particular.net/issues/1011
- [ ] Retrospective

**Comment by mikeminutillo** [comment]
@johnsimons and I are happy to start looking at this if no-one else is available

**Comment by andreasohlund** [comment]
@mauroservienti what do you think?

**Comment by mauroservienti** [comment]
We want you @mikeminutillo! we need you @mikeminutillo!, we.... (cit.)

So, yes, this needs to be done, Have you any overlap with @bording?

**Comment by johnsimons** [comment]
@mikeminutillo and I are working on this one.

@bording I assume you moved to other things right ?

**Comment by bording** [comment]
@johnsimons I had started learning the v6 transport interfaces, and had some spent some time researching RabbitMQ and how other projects use it. I was disappointed to see that are no truly async APIs available with the RabbitMQ .NET client.

If you need additional help, I'm available to work with you on the changes.

**Comment by johnsimons** [comment]
Duplicate of #107
