### ISSUE TITLE
System.InvalidOperationException when using custom IRoutingTopology from same Assembly

### ISSUE THREAD

**Issue by Esbe** [Particular/NServiceBus.RabbitMQ#111]
When using a custom IRoutingTopology as follows:
```
configuration.UseTransport<RabbitMQTransport>()
                .UseRoutingTopology<MyRoutingTopology>();
```
then NServiceBus.Host will throw the following exception if MyRoutingTopology is in the same Assembly as the EndpointConfig class:
```
An unhandled exception of type 'System.InvalidOperationException' occurred in NServiceBus.Host.exe

Additional information: No endpoint configuration found in scanned assemblies. This usually happens when NServiceBus fails to load your assembly containing IConfigureThisEndpoint. Try specifying the type explicitly in the NServiceBus.Host.exe.config using the appSetting key: EndpointConfigurationType, Scanned path: ...
```
Workaround: move the MyRoutingTopology class to a referenced project.

[CustomRoutingTopologyIssue.zip](https://github.com/Particular/NServiceBus.RabbitMQ/files/68665/CustomRoutingTopologyIssue.zip)

**Comment by andreasohlund** [comment]
That's an issue with the host scanning, you need to put the

```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="RabbitMQ.Client" publicKeyToken="89e7d7c5feba84ce" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.7.0" newVersion="3.5.7.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

in a file called NServiceBus.Exe.config in your bin folder as well. Or the other option is to specify the host entrypoint explicitly:

http://docs.particular.net/nservicebus/hosting/nservicebus-host/#configuring-your-endpoint


Does this work for you?

**Comment by andreasohlund** [comment]
I've raised a separate issue to upgrade to latest rabbit client to avoid this issue all together https://github.com/Particular/NServiceBus.RabbitMQ/issues/112

**Comment by Esbe** [comment]
Both suggested approach with the NServiceBus.Exe.config file work. Thanks for pointing the appropriate documentation page.

Note: reading through that page and underlying http://docs.particular.net/nservicebus/hosting/assembly-scanning explanation page, the usage is certainly not "intuitive"...

**Comment by andreasohlund** [comment]
>Note: reading through that page and underlying http://docs.particular.net/nservicebus/hosting/assembly-scanning explanation page, the usage is certainly not "intuitive"...


Yes this area has always been problematic for us, striking the balance between magic that just works and requiring users to be explicit has always been a thin line to walk :(

Any specific parts that you had issues with?

Closing this issue for now, thanks for getting in touch with us!
