### ISSUE TITLE
Endless loop when bus had been stopped while transport is trying to reconnect

### ISSUE THREAD

**Issue by mstavrev** [Particular/NServiceBus.RabbitMQ#1124]
Hello,

There is an issue on the RabbitMQ transport's message pump that's triggered in the following way:
1. Setup an endpoint to have critical error action that stops the endpoint, but does not terminate the process. There is logic in the application to handle multiple endpoints the termination of a bus must not bring down the process.
2. Startup the endpoint and let it connect successfully to the broker
3. Interfere with the broker connection (for example blocking the IP traffic), simulating loss of connectivity.
4. Wait long enough for the circuit breaker to trigger the critical action. The endpoint is shutdown (using Stop)
5. The message pump goes into an endless loop, due to messageProcessing cancellation token being disposed (as the pump had been disposed through the endpoint stop action). The following statement:

https://github.com/Particular/NServiceBus.RabbitMQ/blob/a88332cca5afd7a72da5865be98974194ace5e67/src/NServiceBus.Transport.RabbitMQ/Receiving/MessagePump.cs#L233

throws an exception that's not considered to to be messageProcessing cancellation token related in here:

https://github.com/Particular/NServiceBus.RabbitMQ/blob/a88332cca5afd7a72da5865be98974194ace5e67/src/NServiceBus.Transport.RabbitMQ/Receiving/MessagePump.cs#L238

and as a result, the while loops forever.

The same can be achieved by setting up the critical action to do nothing and attempting to stop the endpoint externally while the pump is inside the reconnect loop. 

I've looked at v7 and the same problem exists there as well. May be the most simplistic approach would be to terminate the loop on a disposed flag, thus letting the pump go down gracefully.

**Comment by SzymonPobiega** [comment]
Hi

Thanks for raising the issue. Does removing the critical action handler constitute a viable workaround for you? The NServiceBus transports have been designed to handle connection issues in a graceful manner so just removing the critical action handler should be fine. The transport will not consume significant resources while trying to re-connect.

In the meantime we'll look into how we could fix the underlying problem.

**Comment by mstavrev** [comment]
Hello,

This is a partial way to deal with the problem, but not entirely. We are bringing up and down endpoints depending on some business logic. E.g. the life-time of endpoints do not coincide with the life-time of the hosting process.
Because of that, it is possible for a broker to becomes inaccessible before our logic no longer needs to work with it and stop the endpoint. That means the endless loop (causing high CPU usage) may be still triggered. The only "work-around" would be not to stop a no longer needed endpoint, but instead leaving it dangling (having its pump operating in the background). That however, may lead to other problems, as if the broker becomes eventually online the endpoint may restore message consumption where this is no longer intended. 

I understand the concept of NServiceBus is more towards decomposing the workload on separate, independent, self-hosted bus-oriented instances, where such an error ideally would terminate the hosting process. However, it isn't something we can go for at the moment.

**Comment by SzymonPobiega** [comment]
@mstavrev could you also open a support case with us so that we have a private channel to discuss anything sensitive?
