### ISSUE TITLE
Update RabbitMQ.Client to 3.6.1

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#117]
Heads up , quite a few breaking changes - http://apicomparer.particular.net/compare/rabbitmq.client/3.5.0...3.6.0

**Comment by bording** [comment]
This has been done in #124 for the v6 release.

**Comment by andreasohlund** [comment]
Reopening since we need to get a compatible version out for core v5

**Comment by bording** [comment]
This has been included in the 3.1.0 release.
