### ISSUE TITLE
Do we need Secondary Receivers in RabbitMQ?

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.RabbitMQ#118]
Connects to Particular/NServiceBus.SqlServer#124

As the solution for the Particular/NServiceBus.RabbitMQ#35, to prevent message duplication we introduced "Secondary Receivers". That was dealing both with pubsub and callbacks.
The callbacks have been moved to a separate package in v6. Do we still need "Secondary Receivers" for proper pubsub?

**Comment by bording** [comment]
Now that the new routing-based callbacks feature has been added to core, the answer to this question is "No, we don't need them."

Everything related to the rabbit-specific secondary receivers has now been removed on the core-v6-update branch.
