### ISSUE TITLE
Immediate retry count does not increase for rabbit messages which are sent to queue without "message_id" property after upgrade to NServiceBus 8

### ISSUE THREAD

**Issue by bruusi** [Particular/NServiceBus.RabbitMQ#1323]
### Describe the suggested improvement

We have noticed that after upgrading to NServiceBus 8 that in certain conditions a message will be stuck on immediate retry if an exception occurs. We have some native Rabbit MQ integrations and if messages which are sent to a queue without specifying the message_id property and the message for some fails with an exception the message is continuously retried with immediate retry and in the logs we see that the retry count is never increased.

We have been able to reproduce it by manually publishing a message through the Rabbit MQ admin interface. A message published without the message_id property which hits a handler with an exception will then be "stuck". If we specify the message_id property it is handled, immediate retries are counted and then the message is delayed (as configured) and is moved to the error queue (or ServiceControl).

We recognize that some of our integrations should improve sending rabbit messages and specify message_id always, but this is not something we are in complete control over so hopefully this is something you would want to look into?

**Comment by andreasohlund** [comment]
Hi @bruusi what version of NServiceBus.RabbitMQ are you on?

Looking at the code a missing message id would throw 

https://github.com/Particular/NServiceBus.RabbitMQ/blob/master/src/NServiceBus.Transport.RabbitMQ/Receiving/MessageConverter.cs#L20

and then cause the message to go straight to the error queue

https://github.com/Particular/NServiceBus.RabbitMQ/blob/master/src/NServiceBus.Transport.RabbitMQ/Receiving/MessagePump.cs#L384

so something is not functioning correctly here since it hits your handler?

**Comment by bruusi** [comment]
Hi @andreasohlund, thanks for your prompt reply. Looks like we are on the correct version but I also see that we have a custom message id strategy in this endpoint. Will dig a bit more on our end.

```
 transport.CustomMessageIdStrategy(deliveryArgs =>
            {
                var id = deliveryArgs.BasicProperties.MessageId;
                if (string.IsNullOrWhiteSpace(id))
                    id = Guid.NewGuid();

                return id;
            });
```

Looks like our third party integration is also going to fix the missing message_id which would solve the issue we have been seeing.

As mentioned I can't remember us having any issues before upgrading but will look more into how this integration endpoint is behaving on our side and let you know of our findings.

**Comment by andreasohlund** [comment]
> if (string.IsNullOrWhiteSpace(id))
                    id = Guid.NewGuid();

That looks problematic, since generating a new Guid each time would lead to infinite retries. Would it be possible to use something deterministic from the message? (perhaps a hash of the body and some header)

But yea having the integration partner set a reliable ID is definitely the way to go

**Comment by bruusi** [comment]
Yes, looks like this is the problem and we will sort this out on our side. Thanks very much for your help and prompt replies!

**Comment by andreasohlund** [comment]
Awesome, I'll go ahead and close this issue for now
