### ISSUE TITLE
Sending to a non-existent endpoint can have unexpected behavior and message loss

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.RabbitMQ#135]
### Current status

<table>
<tr><th></th><th>Publisher Confirms Enabled</th><th>Publisher  Confirms Disabled</th></tr>
<tr><th>ConventionalTopology</th><td><sup>1</sup> :smile: "Channel has been closed" exception for first bad message</td><td><sup>2</sup> :cry: message loss if there are only a few messages, and the occasional `AlreadyClosedException` when the channel closed out from underneath us at various points</td></tr>
<tr><th>DirectTopology</th><td><sup>3</sup> :smile: "Message could not be routed" for first bad message</td><td><sup>4</sup> :smile: : Warning log entry "Message could not be routed"</td></tr>
</table>

---

When an endpoint sends a message to a non-existent endpoint (or one that has never been started at least once so no exchanges/queues have been created for it yet) the behavior varies based on a couple of factors.
### ConventionalRoutingTopology

When using the default ConventionalRoutingTopology, the behavior you see depends on if publisher confirms are enabled or not.

If publisher confirms are enabled, then you will see a `QueueNotFoundException` because we catch an `AlreadyClosedException` and check to see if the channel was closed because the destination exchange didn't exist.

If publisher confirms are disabled, things get weird. In my testing, I've seen the following things:
- no indication that anything was wrong at all
- an `AlreadyClosedException` gets thrown
- no errors, but when shutting the endpoint down the RabbitMQ client throws an `OperationInterruptedException`

Which one of these you get depends on how many messages you're trying to send in a batch (from inside a handler). If you only send one message, then we don't keep the channel alive long enough for the error/closed message to make it back from the server. If we are reusing the channel to send a batch of messages, then eventually we get the `AlreadyClosedException` once the client catches up to the server sending the error/closed message back.

Sometimes when sending a batch, instead of getting the `AlreadyClosedException`, everything would work fine and instead I'd see the `OperationInterruptedException` when the endpoint shut down. I'm still not exactly sure what's going on with that.
### DirectRoutingTopology

With the DirectRoutingTopology, things are a bit more straightforward: You will never be able to tell if you're sending to endpoint that doesn't exist. In this topology, we are using the system-defined default exchange to route messages, so it always exists. That means the channel won't be closed with an error like it is with the ConventionalRoutingTopology. The broker will also send the confirm message (if publisher confirms are enabled) since from its perspective it has received the message. It then will look at the routing key of the message, see that it matches none of the queues bound to the exchange, and will then discard the message.

If publisher confirms are disabled there will be a Warning log created with a message: "Message could not be routed"
### Mandatory flag on sends

For the DirectRoutingTopology, there isn't much we can do because of how RabbitMQ works. There is a `mandatory` flag we could use when sending a message that would cause a message that can't be routed to a queue to be returned to use instead, but given our current channel architecture, we have no way of taking advantage of that. We would need to keep a channel alive long enough after sending a message to receive the returned message, and at most we'd be able to log a warning that it happened.

For the ConventionalRoutingTopology, the `mandatory` flag wouldn't be helpful, because sending to a non-existent exchange is an error that closes the channel. The message isn't returned because as far as the server is concerned it was never accepted in the first place.
### Alternate Exchange setting

RabbitMQ has the concept of the [Alternate Exchange](https://www.rabbitmq.com/ae.html) that lets you designate an alternate exchange to route a message to if the original exchange can't route the message. For the DirectRoutingTopology, this could be used to route those messages to a special exchange/queue when the default system exchange can't find a queue.

However, this wouldn't work for the ConventionalRoutingTopology, since the AE setting has to be applied to the exchange, and in this scenario, the destination exchange doesn't exist.

---

One other thing I wanted to point out related to this is when sending a batch of messages in the ConventionalRoutingTopology/publisher confirms enabled scenario, if in the middle of your batch you have one bad message, you could end up with an `AlreadyClosedException` while still trying to send messages. At that point some your messages will have been sent, but some of them won't have been.

---
## Plan of Attack
- [x] Add publish channel pooling architecture that enables us to take advantage of `basic.return` messages from the `mandatory` flag: #136 
- [x] Enable the `mandatory` flag for message sends, but keep it disabled for publishes
- [ ] Determine what additional changes (if any) need to be made to the ConventionalRoutingTopology

**Comment by volak** [comment]
I am seeing a very large proportion of my messages ending with basic.return [http://i.imgur.com/vd5cWZu.png](imgur)

Would this behavior be related to this bug?  I am trying to debug why rabbitmq is finding my messages unroutable, especially since some messages of the same type go through fine..

**Comment by bording** [comment]
@volak It's possible that what you're seeing is related. For all of the currently released versions of the transport, we turn on the `mandatory` flag for all sends and publishes.

What routing topology are you using? Do you have publisher confirms enabled?

**Comment by volak** [comment]
@bording I am using direct topology, and I've tried with and without confirms - same results.

I don't suppose theres a way to configure the client to report basic.return messages and where they were trying to go?

**Comment by bording** [comment]
@volak At the moment, the transport doesn't have a way to surface the basic.return messages, but that is something I'm looking into supporting for the next major release of the transport.

Since you're using the direct topology, if you'd like to be able to inspect the messages that are triggering those returns, I'd recommend taking a look at RabbitMQ's [Alternate Exchange](https://www.rabbitmq.com/ae.html) feature.

First, you'd need to create a fanout exchange and bind it to a queue. This will be your alternate exchange.

Then, you would add the AE setting via policy to the `(AMQP default)` exchange to capture message sends.

We're also currently enabling the `mandatory` flag when events are published, but an unroutable event isn't really considered an error. It just means that you have no subscribers for that event. By default, the direct topology uses the `amq.topic` exchange to publish events, so you could add the AE setting to that exchange as well.

Once you've done this, any messages that couldn't be routed will be sent to the alternate exchange instead, and should be delivered to the queue that you've manually bound to it. You can then inspect those messages through the RabbitMQ management UI.

**Comment by andreasohlund** [comment]
@bording can you list the people on the taskforce and move this into in-progress ?

**Comment by bording** [comment]
I have added the task force members, created an initial PoA, and moved this into In Progress.

**Comment by WojcikMike** [comment]
Current status:
* we are finishing #136 which will allow us to use mandatory flag to ensure that message is routed. ATM we have 1 acceptance test failing and we are investigating why.

After fixing the above we will move further with Plan of Attack.

**Comment by andreasohlund** [comment]
Since we're at our WIP limit of 10 and work needs to start on https://github.com/Particular/PlatformDevelopment/issues/702 the squad ( me and @adamralph ) has decided to temporarily stop work on this one since 702 is a higher priority.

The reasoning:

* This one is not urgent, needs to be done before final release of rabbit for v6 though
* There is no proper task force since @mat-mcloughlin is tied up in https://github.com/Particular/NServiceBus.Testing/issues/29

This issue has been moved to "Next in line" so it will restart as soon as possible.

@bording @WojcikMike please join https://github.com/Particular/PlatformDevelopment/issues/702 if appropriate. If not please find other taskforces to join.

sorry for the inconvenience

**Comment by andreasohlund** [comment]
@bording @WojcikMike this one can go back to progress again if you can find a 3:d member. (assuming the @mat-mcloughlin is still tied of with testing?)

**Comment by mat-mcloughlin** [comment]
I'm afraid I'm still tied up in testing

**Comment by WojcikMike** [comment]
No worries @mat-mcloughlin I removed you from TF and I am looking for a replacement. When you will be available let us know.

**Comment by andreasohlund** [comment]
https://github.com/Particular/PlatformDevelopment/issues/719 is more important at the moment. Moving this one to backlog for now

**Comment by johnsimons** [comment]
Fixed in #146

**Comment by bording** [comment]
This isn't related to #146

**Comment by johnsimons** [comment]
oops, my mistake

**Comment by bording** [comment]
Now that channel pooling has been implemented and the mandatory flag has been enabled for sends, I wanted to see what things look like.

I tested things using the following sample application:

```csharp
class Program
{
    static void Main(string[] args)
    {
        MainAsync().GetAwaiter().GetResult();
    }

    static async Task MainAsync()
    {
        var config = new EndpointConfiguration("sender");

        var usePublisherConfirms = false;
        config.UseTransport<RabbitMQTransport>().ConnectionString($"host=rabbit;UsePublisherConfirms={usePublisherConfirms}");//.UseDirectRoutingTopology();
        config.SendOnly();

        var endpoint = await Endpoint.Start(config);

        var numberMessages = 1000;

        for (int i = 0; i < numberMessages; i++)
        {
            Console.WriteLine($"Sending message {i}");
            await endpoint.Send("foo", new Message());
        }

        Console.WriteLine("Press key to quit");
        Console.ReadKey();

        await endpoint.Stop();
    }
}

class Message : ICommand { }
```
### ConventionalRoutingTopology

Things are largely looking the same here. When publisher confirms are enabled, we are seeing "Channel has been closed" `Exception`s coming from the `ConfirmsAwareChannel`. [link](https://github.com/Particular/NServiceBus.RabbitMQ/blob/release-4.0.0/src/NServiceBus.RabbitMQ/Connection/ConfirmsAwareChannel.cs#L195)

When publisher confirms are disabled, we're still seeing `AlreadyClosedException`s at some point in the message sending, or no error if there are few enough messages.

With my current testing, I haven't yet seen the weird `OperationInterruptedException` on shutdown, that I was seeing before occasionally, so that's good.

### DirectRoutingTopology

Better news here! With publisher confirms enabled, we now get "Message could not be routed" `Exception`s from the `ConfirmsAwareChannel`. [link](https://github.com/Particular/NServiceBus.RabbitMQ/blob/release-4.0.0/src/NServiceBus.RabbitMQ/Connection/ConfirmsAwareChannel.cs#L166)

At the moment, we're still not seeing anything when publisher confirms are disabled, but that could be tweaked somewhat. Currently, we're only registering the `Channel_BasicReturn` event handler when [publisher confirms are enabled.](https://github.com/Particular/NServiceBus.RabbitMQ/blob/release-4.0.0/src/NServiceBus.RabbitMQ/Connection/ConfirmsAwareChannel.cs#L25) However, if we register it all the time, then we could get a [log message](https://github.com/Particular/NServiceBus.RabbitMQ/blob/release-4.0.0/src/NServiceBus.RabbitMQ/Connection/ConfirmsAwareChannel.cs#L179) when a message couldn't be delivered. There still wouldn't be a way to surface an exception back up to awaited `Send`, but perhaps a log message is enough here? Regardless, this seems like a worthwhile change to make.

## Where does that leave us?

So, assuming we do go ahead and make the  `Channel_BasicReturn` event handler registration tweak, here's where we currently stand:
- When publisher confirms are enabled, we now get exceptions on the very first bad message, for both topologies. :tada: 
- We're still getting the channel closed out from underneath us at various points when using the `ConventionalRoutingTopology`, which leads to inconsistent behavior when publisher confirms are disabled. :cry: 
- Behavior is still inconsistent between topologies when publisher confirms are disabled. :cry: 

Ideally, I'd like to see the behavior be the same in all scenarios for both topologies. The first step in making that happen would be to make some changes to the `ConventionalRoutingTopology` which would prevent it from closing the channel. To do this, we'd need to have the sending endpoint verify/declare the destination exchange before trying to send to it for the first time, like it currently does before publishing. If it did this, then the `Channel_BasicReturn` event handler would be called instead of closing the channel, as it is for the `DirectRoutingTopolgy`.

The one potential downside to making this change, if the sender and the destination endpoints have different durable messages settings, then the declared exchanges wouldn't match. However, this is already true for the subscription type exchanges that get created, so perhaps this isn't worth worrying about?

The other thing we need to decide is if logging when publisher confirms are disabled is enough. If not, what other behavior would be desirable given that there isn't a way to get an exception back to the `Send` call? Perhaps something using the Alternate Exchange feature to route these messages into another queue?

**Comment by adamralph** [comment]
@Particular/rabbitmq-transport-maintainers discussed this today and agreed to decouple the fixing of this bug from the V6 Launch (of NServiceBus). Either can happen independently of another.

**Comment by adamralph** [comment]
Defaulting to medium impact whilst we investigate this.

**Comment by adamralph** [comment]
As discussed, I'll draw up a matrix of all the possible behaviours with dimensions "Topology", "PublisherConfirms", and "Send/Publish".

**Comment by adamralph** [comment]
@Particular/rabbitmq-transport-maintainers I started drawing the matrix but I got stuck quite quickly (see the top of the description of this issue) and I'll need some help.

**Comment by adamralph** [comment]
@adamralph
> @bording: OK, I've removed the column and done my best to fill in all four cases. Can you review? Did I get them right?

@bording 
> That seems to capture the core differences, since it points out that we are still getting different exceptions for the confirms enabled column

@adamralph
> ok, great. The picture is much clearer for me now

@bording 
> Does that help understanding what I'm proposing for additional changes, and how those changes would make the behavior identical for both topologies?

@adamralph
> I think it does. So the first change, registering `Channel_BasicReturn` regardless of publisher confirms, will mean we get a log message in square 4 to say a message was lost (I've numbered the squares)
> the next change, declaring the destination exchange before sending, would make 1 behave like 3
> or would it make all squares behave like 3?

@bording 
> 1 would behave like 3, and 2 would behave like 4

@adamralph
> ah, yes
> well, that makes sense, because publish confirms are specifically designed to move the behaviour from that of 2 and 4 to that of 1 and 3

@bording 
> exactly

**Comment by adamralph** [comment]
Blocked on #185.

Perhaps "blocked" isn't entirely accurate, but we're holding off until #185 is done because it will make writing an acceptance test easy.

**Comment by adamralph** [comment]
Marking as size S and maintainer prio since #185 will make this easy to write a test for and fix.

**Comment by adamralph** [comment]
Based on our discussion yesterday I've reduced the impact to S.

**Comment by adamralph** [comment]
Unassigned myself for now. We've boiled it down to a small so after it gets unblocked by #185 I guess whoever picks it up can just assign themselves.

**Comment by WojcikMike** [comment]
As the https://github.com/Particular/NServiceBus.RabbitMQ/issues/184 was solved the current state changed a bit, Main issue description updated to reflect the reality.

**Comment by adamralph** [comment]
Non longer blocked on #185

**Comment by adamralph** [comment]
Added to 4.0.0 milestone since, at the moment, we are saying this is a blocker for 4.0.0 RC, but that is under discussion (AFAIK this is an existing problem in 3.x and is no worse in 4.0).

**Comment by adamralph** [comment]
@Particular/rabbitmq-transport-maintainers discussed this and decided that there is no good way to fix this. Instead, we will document a warning.
