### ISSUE TITLE
Audits/forwards might be routed to wrong destination

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.RabbitMQ#142]
RabbitMQ transport for V6 might have a bug similar to this SQL Server transport one https://github.com/Particular/NServiceBus.SqlServer/issues/202

**Comment by SzymonPobiega** [comment]
@Particular/rabbitmq-transport-maintainers please verify if RabbitMQ is affected.

**Comment by SimonCropp** [comment]
there is a sql repro here https://github.com/SimonCropp/Bugs/tree/master/SqlVersionInCompat that can be converted to rabbit to verify

**Comment by WojcikMike** [comment]
@SzymonPobiega @SimonCropp I convereted Simon's sample and the RabbitMQ is affected

**Comment by SimonCropp** [comment]
@WojcikMike ok cool. 

If anyone else makes progress on this today can u update one of the issues. i will be bake online in 13 hours

**Comment by adamralph** [comment]
Just to clarify - this was both introduced and fixed in 4.0 (for core 6.0), correct?

**Comment by bording** [comment]
> Just to clarify - this was both introduced and fixed in 4.0 (for core 6.0), correct?

That is correct.
