### ISSUE TITLE
Make ConnectionConfiguration public

### ISSUE THREAD

**Issue by twenzel** [Particular/NServiceBus.RabbitMQ#1470]
### Describe the suggested improvement

Sometimes you need to deal with the RabbitMQ connection string for other reasons. Therefor you've to parse the connection string and handle the different schemas (amqp or sql-style).

You already have a perfect implementation, the `NServiceBus.Transport.RabbitMQ.ConnectionConfiguration.Create` method. Unfortunately it cannot be used because the `ConnectionConfiguration` class is private.

Please make this class public so it can be re-used.

**Comment by andreasohlund** [comment]
@twenzel thanks for raising this and the corresponding PR, to better evaluate the proposal can you share some details on the use case that requires the connection string to be parsed? This functionality would likely sit better in the RabbitMQ client, have you checked if something similar is available in the RabbitMQ client library?

**Comment by twenzel** [comment]
Unfortunately,I didn't found anything in the RabbitMQ client library.
Use case: I've an connection string (might be amqp or NServiceBus) and want to fill the ConnectionProperties of the RabbitMQ.Client.ConnectionFactory.

This whole story is done to because we want to have 2 different ConnectionStrings. One with administrative permissions and one regular permissions. The "Admin-ConnectionString" is used to create the infrastructure (Exchanges and Queues).

**Comment by andreasohlund** [comment]
@twenzel we discussed this internally we are reluctant to add public types that aren't strictly part of our public API. Feel free to copy the parser into your code base to make use of it and tweak it as needed.

That said, is there anything we are missing in our API related to how you can configure our transport that would avoid you having to parse those connection strings in the first place?

**Comment by twenzel** [comment]
@andreasohlund Thanks for clarify. After having a chat with our team we'll change our current approach (having a dedicated "admin" connection string for the exchange and queue creation). As you already mentioned in your [Best practices guide](https://docs.particular.net/nservicebus/best-practices), we'll start scripting the infrastructure with RabbitMQ Kubernetes Operator.
