### ISSUE TITLE
Remove ConnectionManager

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.RabbitMQ#149]
Currently, we still have both `ConnectionManager` and `ConnectionFactory` classes. As mentioned in https://github.com/Particular/NServiceBus.RabbitMQ/issues/74#issuecomment-201040218, the scope of what `ConnectionManager` is doing has been decreased. At this point it is only being used to manage the publish connection and passing along the creation of the admin connection to the connection factory:

https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/Connection/ConnectionManager.cs

Instead of keeping `ConnectionManager` around just to pass it into `ChannelProvider`, I think it makes sense kill `ConnectionManager` and just pass `ConnectionFactory` around directly.

This would mean that `ChannelProvider` would get a `ConnectionFactory` and create its own publish connection when it needs it, and then would be responsible for closing it when the endpoint is stopping.

This approach works because at that point we would only ever need to be "creating" connections and the two places that keep connections open (`ChannelProvider` and `MessagePump`) can just deal with the created connection directly.

The `MessagePump` was originally designed this way because it needed to create a specific `ConnectionFactory` to pass in a custom scheduler, but I've cleaned that up a bit, and it no longer requires the custom scheduler. 550664404c2563d01096cec25cca283e038eb95d

Because of this, we could decide on an alternate approach. The `MessagePump` could once again get a "managed" connection from `ConnectionManager`, and then it would use that connection to create a channel. 

This would put the `ConnectionManager` back in charge of connection lifetimes.

Currently, as a side effect of the `MessagePump` being responsible for creating a connection, each `MessagePump` instance creates its own connection, so each queue being consumed (main, optional instance queue, satellites) has a separate connection in addition to a separate channel. I was able to take advantage of this and the purpose of each connection is set differently instead of having a generic "consume" purpose: https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/Receiving/MessagePump.cs#L74

This is nice when viewing the connections from the management UI, and we'd lose it if we went back to the `ConnectionManager` being in charge.

Thoughts? 

@Particular/rabbitmq-transport-maintainers

**Comment by andreasohlund** [comment]
:heart:
