### ISSUE TITLE
Set up alerts for RabbitMQ.Client releases

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#154]
To go to at least @Particular/rabbitmq-transport-maintainers

**Comment by SimonCropp** [comment]
i configured an IFTT rule to email me for new RabbitMQ.Client releases

**Comment by adamralph** [comment]
:+1: I guess we'll do the same, and use an email alias for the maintainers.

**Comment by adamralph** [comment]
This looks like an easy solution https://twitter.com/holman/status/793561589290979328

**Comment by SimonCropp** [comment]
isnt this a 5min task? should it still be open?

**Comment by adamralph** [comment]
@SimonCropp it probably is a 5 minute task but I'm not sure how to set up an IFTTT rule to pick up a NuGet release. I think I'd rather push it to a Slack channel than use email. Can you share the method you used to set up the incoming event in IFTTT?

**Comment by WojcikMike** [comment]
I've set up notifications using: libraries.io (that you suggested @adamralph), but this is only to my mail.

**Comment by WojcikMike** [comment]
@adamralph I think I've set up an alert. Using https://github.com/rabbitmq/rabbitmq-dotnet-client/releases.atom as a feed. And when the new item occurs it will post to our slack channel (maintainers-rabbit)

**Comment by SimonCropp** [comment]
here is my recipe 

![image](https://cloud.githubusercontent.com/assets/122666/22504537/017cd650-e8cb-11e6-9a05-e22e6360ba94.png)

**Comment by adamralph** [comment]
Thanks @SimonCropp.

@WojcikMike thanks for that. Would you mind changing it to use the NuGet feed?

**Comment by WojcikMike** [comment]
@adamralph is there RSS feed for nuget?

**Comment by adamralph** [comment]
@WojcikMike from @SimonCropp 's recipe: http://nugetfeed.org/list/packages/RabbitMQ.Client

**Comment by WojcikMike** [comment]
Alerts are set up, The iftt applet was tested using adams repo.
