### ISSUE TITLE
Introduce retries on sends

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#17]
With the new pipelines in 4.3 (not exposed until 4.4) we can now very easily do retries on sends (and also fallback to alternate brokers) by just injecting a new behavior into the outgoing pipeline

@fhalim, @thirkcircus, @gsogol Ifaik one of you guys asked for this type of feature?

**Comment by ramonsmits** [comment]
@andreasohlund what remains to be done here?

**Comment by andreasohlund** [comment]
The idea here was to add retries on outgoing operations but since most of those happen from a message handler which has retries anyway I'm not sure this brings enough value. When doing sends outside a message handler users could just retry the operation themselves using Polly or some custom code.

Closing this for now
