### ISSUE TITLE
Non-default port settings are being ignored

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.RabbitMQ#175]
The default port for RabbitMQ connections is 5672. Currently, this is the only port that the transport will attempt to connect to, even when a different port has been configured in the connection string. This also prevents AMQPS connections from working, because these connections need to be established on port 5671.

This problem was introduced when we updated to 3.6.2 of the RabbitMQ client library, which is ignoring all port settings and always using 5672.

**Comment by adamralph** [comment]
Re-opening until we merge to release-4.0.0
