### ISSUE TITLE
Samples link on github home page is broken

### ISSUE THREAD

**Issue by jpv001** [Particular/NServiceBus.RabbitMQ#177]
The link https://github.com/Particular/NServiceBus.RabbitMQ.Samples results in a 404.

**Comment by SimonCropp** [comment]
can u try now

**Comment by SimonCropp** [comment]
as in i updated the link on the readme to http://docs.particular.net/samples/rabbitmq/

**Comment by jpv001** [comment]
All sorted, a nice easy one for a change!

**Comment by SimonCropp** [comment]
@jpv001 yeah sorry about that. it is on the todo list to script the updating of all our readme files based on a template... so much to do :)

**Comment by adamralph** [comment]
Thanks @jpv001 for raising this, and thanks @SimonCropp for fixing!
