### ISSUE TITLE
Messages may be silently lost when using DirectTopology and Publisher Confirms are disabled

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#184]
Spun off from #135.

When using DirectTopology and Publisher Confirms are disabled, if a message is sent before the receiver has set up it's queue, the message will currently be lost silently. By subscribing to the BasicReturn event, we can log a message in this case.

We plan to implement this feature in 4.0. The 3.x codebase does not lend itself to implementing this feature without a significant amount of rework.

**Comment by adamralph** [comment]
@Particular/rabbitmq-transport-maintainers please review the description for correctness.

**Comment by udidahan** [comment]
I wouldn't call this a feature - if anything it's a fix for the bug of messages being lost silently.

**Comment by adamralph** [comment]
Fixed in #195

**Comment by mikeminutillo** [comment]
Should there be a "known issues" list for version 3.x of Rabbit Transport where we can list this?

**Comment by adamralph** [comment]
@mikeminutillo good idea.

Do you know if there is already a place for this in docs? Or would it be a new page under http://docs.particular.net/nservicebus/rabbitmq/ ? /cc @Particular/docs-maintainers
