### ISSUE TITLE
Provide programmatic configuration of Publisher Confirms

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#185]

**Comment by andreasohlund** [comment]
Is the idea to add a extension on `SendOptions`?

```

var options = new SendOptions();

options.EnablePublisherConfirms();

await context.Send(new Message(),options);

```

or similar?

**Comment by bording** [comment]
It can't be enabled/disabled a per-message basis. Currently the only way to configure it is via a property on the connection string. Being able to control it via a [setting extension](https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/Configuration/RabbitMQTransportSettingsExtensions.cs) is what we're looking to add.

**Comment by adamralph** [comment]
Closed by #196

**Comment by adamralph** [comment]
Re-opening since docs are not updated.

**Comment by WojcikMike** [comment]
Doco PR opened, now we need to wait for this feature to get to nuget so that snippets would build

**Comment by adamralph** [comment]
In that case, shall we close this now, since there's nothing more we can do until we've released RC?

**Comment by WojcikMike** [comment]
Yeah, I think so
