### ISSUE TITLE
Separate and de-dup connection string docs

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus.RabbitMQ#191]
I noticed that we have some duplication (?) in the doco, see http://docs.particular.net/nservicebus/rabbitmq/configuration-api#rabbitmq-connection-string and http://docs.particular.net/nservicebus/rabbitmq/connection-strings

We should either move all info about connection strings to a separate page or delete the connection strings page.

The first approach would be better, because of the number of options here http://docs.particular.net/nservicebus/rabbitmq/configuration-api#rabbitmq-connection-string-connection-string-options it'll be easier to read and search for info.

**Comment by adamralph** [comment]
Thanks for raising @weralabaj

**Comment by WojcikMike** [comment]
Mr @SimonCropp moved all the options hence closing this issue
