### ISSUE TITLE
Beta is throwing NotSupportedException when PrefetchCount is present in connection string

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.RabbitMQ#193]
Beta is throwing NotSupportedException when PrefetchCount is present in connection string value.

> System.NotSupportedException: The 'PrefetchCount' connection string option has been removed. Use 'EndpointConfiguration.LimitMessageProcessingConcurrencyTo' instead.

Instead of an exception consider to write a WARN log entry. It's not common to throw when an unsupported or unknown argument is present in a connection string.

**Comment by SimonCropp** [comment]
Imho the current behaviour is correct. It stops people from configuring something, with the expectation they have succeded. Where the warning could possibly missed

**Comment by andreasohlund** [comment]
:+1: to throw, ok to close? (doco seems ok http://docs.particular.net/nservicebus/upgrades/rabbitmq-3to4#connection-string-options-prefetchcount)

**Comment by WojcikMike** [comment]
I agree, we should close this. If one disagrees and want to argue please reopen

**Comment by adamralph** [comment]
Updated the title so it represent something that we "Won't fix".
