### ISSUE TITLE
Expose prefetch count API and optimise default

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#198]
There still seem to be conversations happening about prefetch count being sub-optimal in 4.0 (NSB 6.0) vs. that used in 3.0 (NSB 5.x).

I couldn't find an existing issue which captures this concern so I raised this one. Perhaps things have moved along in my absence to make this issue redundant.

**Comment by bording** [comment]
@adamralph I had started looking into core v5 vs v6 perf when I ran into https://github.com/Particular/V6Launch/issues/108.

Once we get that sorted upstream in the client, then we should be on stable ground again to be able get some meaningful numbers for perf comparisons.

At that point, I can see there being some changes to prefetch count, or possibly even some way to add multiple consumers.

**Comment by adamralph** [comment]
Raised a docs PR https://github.com/Particular/docs.particular.net/pull/1908

**Comment by adamralph** [comment]
Note that we'll have to update both http://docs.particular.net/nservicebus/rabbitmq/connection-settings?version=Rabbit_4 and http://docs.particular.net/nservicebus/upgrades/rabbitmq-3to4 as part of this.
