### ISSUE TITLE
Update docs samples and snippets to 3.4.0

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#200]

**Comment by adamralph** [comment]
My mistake. Our dependency is

`RabbitMQ.Client (>= 3.6.3 && < 3.7.0)`

**Comment by adamralph** [comment]
Blocked on https://github.com/Particular/NServiceBus.RabbitMQ/issues/201

**Comment by adamralph** [comment]
Blocked on 3.4.0 release.

**Comment by WojcikMike** [comment]
fixed by: https://github.com/Particular/docs.particular.net/pull/1900
