### ISSUE TITLE
Show all violations when throwing an exception for obsolete connection string parameters

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus.RabbitMQ#202]
Currently in ConnectionStringParser we check if connection string contains obsoleted values and exception is thrown like in here:
https://github.com/Particular/NServiceBus.RabbitMQ/blob/release-4.0.0/src/NServiceBus.RabbitMQ/Configuration/ConnectionStringParser.cs#L49-L56

We should modify the behavior to throw exception including all obsoleted parameters in connection string.

Thanks to that user after running application once will know which connection string parameters were obsoleted

**Comment by WojcikMike** [comment]
This issue was created as a result of the following conversation:
https://github.com/Particular/NServiceBus.RabbitMQ/pull/196#discussion_r77508873

**Comment by adamralph** [comment]
Since this is a (desirable) behavioural change, shall we change the title to something like "Show all violations when throwing an exception for obsolete connection string parameters"?

**Comment by WojcikMike** [comment]
Thanks @adamralph changed

**Comment by adamralph** [comment]
@WojcikMike I've changed it from a refactoring to a feature (since it's a behavioural change).

**Comment by bording** [comment]
One thing to make sure is considered if this change gets made is that the [ParseHosts](https://github.com/Particular/NServiceBus.RabbitMQ/blob/release-4.0.0/src/NServiceBus.RabbitMQ/Configuration/ConnectionStringParser.cs#L88) method that gets called before the other checks also has a check that should probably be included.

**Comment by adamralph** [comment]
This will be in the next 4.x release.
