### ISSUE TITLE
Set default parameters in SettingsHolder

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus.RabbitMQ#203]
This issue is a result of the following conversation: 
https://github.com/Particular/NServiceBus.RabbitMQ/pull/196#discussion_r77519564

By setting the default values in SettingsHolder we could use SettingsHolder.Get to get default or overriden value. Otheriwse we are forced to use syntex as below:
https://github.com/Particular/NServiceBus.RabbitMQ/blob/release-4.0.0/src/NServiceBus.RabbitMQ/RabbitMQTransportInfrastructure.cs#L39-L43

**Comment by WojcikMike** [comment]
I think our experiment with the PR: https://github.com/Particular/NServiceBus.RabbitMQ/pull/260
showed that at the moment there is little value in it. Because of that I will close the issue for now.

**Comment by adamralph** [comment]
Added withdrawn label.
