### ISSUE TITLE
Native timeouts

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#234]
Spun off from https://github.com/Particular/NServiceBus/issues/4085

Currently, I've no idea if this is feasible with RabbitMQ.

**Comment by WojcikMike** [comment]
An idea presented by @bording would be to implement using:
https://github.com/rabbitmq/rabbitmq-delayed-message-exchange
https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/

But at this time it is experimental plugin. So there is a risk associated with that action. However we could spike it, and see how it works

**Comment by adamralph** [comment]
If the plug-in ever comes out of experimental status, but remains a plug-in, we'd also have to decide on our policy regarding the requirement of plug-ins for our features.

**Comment by bording** [comment]
I've come up with an idea that doesn't require that plugin. I hope to have a spike ready soon to try out.

**Comment by adamralph** [comment]
Meeting scheduled for Thu 20th Oct 13:30 UTC.

**Comment by MarcinHoppe** [comment]
@Particular/rabbitmq-transport-maintainers Have you reached a conclusion on this topic?

**Comment by adamralph** [comment]
@MarcinHoppe we had our meeting yesterday. I will write up the results on this issue today, as soon as I have time.

**Comment by adamralph** [comment]
In summary, we are considering two approaches:

### Method 1 "Queue per delay value"

This method creates a queue with a time-to-live (TTL) equal to the delay value for a given message. The message is sent to that queue and when it expires it is sent to the destination queue.

### Method 2 "Queue per delay bit"

This method creates 32 queues each with a TTL representing a bit in the largest possible delay value (32 bits gives a maxiumum range of ~136 years). A given message is sent to the queue representing the most significant bit set to 1 in its delay value and when it expires it is sent to the queue representing the next less significant bit set to 1. When it expires from the last queue it is sent to the destination queue.
--
We will consider which, if any approach to take, and then raise another issue to get it done.

I'm also closing the spikes now as they have served their purpose.
