### ISSUE TITLE
Create end to end tests using ServiceControl

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#235]

**Comment by adamralph** [comment]
From @mikeminutillo:

@Particular/rabbitmq-transport-maintainers 

The two test cases currently developed look like this:

## Case 1 - Retry
- Endpoint A send Message to Endpoint B
- Endpoint B fails to process Message and forwards it to Error Queue
- ServiceControl picks up Message
- Message is retried via ServiceControl API
- Endpoint B successfully processes Message

## Case 2 - Retry with Reply
- As above except that Endpoint B sends a Reply when processing Message
- Test is successful when Endpoint A successfully processes Reply

Now what we need are configuration options that may interfere with these tests.

We are looking for configuration options for RabbitMQ which will result in a compatibility issues between V5 and V6 as this is where most issues integrating with ServiceControl exist. Remember that SC runs on the Core V5 version of the transport so any new feature s introduced solely for Core V6 *may* cause problems for SC as well.

We already have separate configurations for Conventional Routing Topology (the default) and Direct Routing Topology. Are there any other configuration options that we need to test?

**Comment by adamralph** [comment]
From @bording:

@mikeminutillo Looking over the [configuration docs](http://docs.particular.net/nservicebus/rabbitmq/configuration-api) I'm not seeing anything else that I could think would interfere with those tests.

When enabling the Direct Routing Topology, it does let you override the default conventions for the routing key and exchange name that are used for publishing events, so you'd want those to match for the endpoints that are talking to each other, including SC. Assuming you've got a way to set those for SC, then I think that should be fine too.

**Comment by ramonsmits** [comment]
@adamralph @mike Why is SC involved in these scenarios? Was that because back then SC was using Core 5? It this still relevant as SC is not using Core 5 anymore?

**Comment by mikeminutillo** [comment]
It was the round-trip through SC that was causing the problem because SC was expecting that the raw transport wouldn't modify what it was given. i.e. If we hand off a message with a ReplyToAddress, we don't want the transport to overwrite the ReplyToAddress with the ServiceControl address. It was (and still is) fixed, but we don't push any tests from SC to the transports to verify that behavior so we could in theory break it again. 

I think this is a bigger concern than this repo and should maybe move the the Architecture level. I definitely wouldn't pick it up as a part of an enhancement release.

**Comment by ramonsmits** [comment]
@Particular/platform-architecture-squad As to @mikeminutillo his suggestion, shall we move this to your repo?

**Comment by danielmarbach** [comment]
@ramonsmits I'll bring it up in the next sync.

**Comment by danielmarbach** [comment]
Discussed this in the sync. Given the age of this issue and the problem of upgrading from v5 to v6 and all the efforts that have been going into test coverage around service control we feel this can be safely closed.

Service Control test suite runs well selected end to end tests with the rabbitmq transport in both topologies configured. As long as ServiceControl is still coupled to NServiceBus there can still be cases that cause friction but we expect those cases to be discovered during the acceptance tests runs.
