### ISSUE TITLE
Switch to single build config for CI

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#236]
@andreasohlund recently switched NServiceBus to a single build config for CI. We should follow suit, which will remove the friction of having to switch between 3.x and 4.x build configs.

**Comment by andreasohlund** [comment]
Related to https://github.com/Particular/PlatformDevelopment/issues/951

**Comment by andreasohlund** [comment]
See https://github.com/Particular/PlatformDevelopment/issues/951 for instructions

**Comment by adamralph** [comment]
Done!
