### ISSUE TITLE
Message missing CorrelationId can cause retries to loop endlessly

### ISSUE THREAD

**Issue by jenspettersson** [Particular/NServiceBus.RabbitMQ#239]
@andreasohlund told me to open an issue here as we've been debugging a failed message that was retried from Service Pulse that got stuck in an endless loop, totally ignoring all recoverability settings.

It seems that if you dispatch a message from a 'Satellite' that a regular `IHandleMessages<...>` handles with  an exception, all the recoverability settings is applied like it should, like immediate retry/delayed retries. That message gets pushed to the error queue and picked up by ServicePulse.

If you THEN retry this message from ServicePulse and it once again fails in the handler, but now it just keeps retrying immediately forever and fills the logs blazingly fast ;)

After investigation I found that if a message is dispatched from a Satellite and you don't manually add `messageContext.Headers.Add(Headers.CorrelationId, messageContext.MessageId);` this issue is happening if the message fails somewhere and then retried from ServicePulse.

I can provide code samples where this is reproduced if needed.

**Comment by adamralph** [comment]
@jenspettersson thanks for raising this. @andreasohlund also gave a heads up to @Particular/rabbitmq-transport-maintainers and we're on the case...

BTW - he mentioned that you are using the latest RC packages (NServiceBus 6.0.0-rc0003 and NServiceBus RabbitMQ 4.0.0-rc0004), is that correct?

> I can provide code samples where this is reproduced if needed.

👍 that would be an enormous help.

**Comment by jenspettersson** [comment]
@adamralph 
`NServiceBus 6.0.0-rc0003`
`NServiceBus.RabbitMQ 4.0.0-rc0004`

And here's a repo with a project that reproduces this: https://github.com/jenspettersson/NServiceBus.Labs

Just change the connection string to rabbit in the app.config and make sure you have a ServicePulse instance listening to the error queue.

When the service is running, go to your RabbitMQ management gui and manually publish a string to the queue `LAB.LegacyQueue` 

![image](https://cloud.githubusercontent.com/assets/125493/18989791/1e7bef76-870e-11e6-8ae9-aaf274b565a0.png)

The satellite will take whatever string you publish a `MyMessage` event containing the string and if it's 'fail' the handler will throw. 1 immediate retry, 1 delayed (5 sec).

Go to service pulse and retry that message and watch it loop... 

To make it work, uncomment https://github.com/jenspettersson/NServiceBus.Labs/blob/master/Nsb.RetryLoop/Nsb.RetryLoop.Client/LegacySatellite.cs#L46

Not sure if it's a bug but it's easy to miss and may cause a lot of pain...

**Comment by andreasohlund** [comment]
A quick glance and the code (both core and rabbit) shows no funky usage of the correlation id so I don't get how that could cause the infinite loop. I'll digg some more

**Comment by adamralph** [comment]
It turns out that either [ServicePulse](https://github.com/Particular/ServicePulse) (or the back end, [ServiceControl](https://github.com/Particular/ServiceControl)) is adding a `null` `CorrelationId` header to the message when it is retried.

In the RabbitMQ transport, we use the value of the `CorrelationId` header from the message to [set the `CorrelationId` for the RabbitMQ client](https://github.com/Particular/NServiceBus.RabbitMQ/blob/7aa17f7b156215a62a4403a4604e8976e9771a73/src/NServiceBus.RabbitMQ/Sending/BasicPropertiesExtensions.cs#L20).

When we try and send that message, the RabbitMQ client blows up, so we requeue the message for another attempt, and hence the endless loop.

(Kudos to @bording for diagnosing all this.)

The immediate fix is to stop setting the `null` `CorrelationId` header in ServiceControl/ServicePulse. We're in the process of tracking down exactly where that happens and we'll raise an appropriate issue to get that fixed and link it here.

We'll also make the RabbitMQ transport immune to a `null` `CorrelationId` and we'll check our use of other headers at the same time for similar vulnerabilities. Given that the immediate problem is going to be fixed in ServicePulse/ServiceControl, and that we are already in RC for 4.0.0, we'll schedule this fix for the next minor release, 4.1.0.

**Comment by jenspettersson** [comment]
Thanks for the info @adamralph!

**Comment by WojcikMike** [comment]
I found that issue is in ServiceControl in terms of setting CorrelationId to null and I created an issue for that: https://github.com/Particular/ServiceControl/issues/794

**Comment by johnsimons** [comment]
@WojcikMike @adamralph  @bording  I understand the issue, but what I don't understand is what do we set `CorrelationId` to if not null ?
[As you can see in ServiceControl](https://github.com/Particular/ServiceControl/blob/0b0c6c6cf9b8e4048cb2256a60647b9544fa3e34/src/ServiceControl/Contracts/Operations/PhysicalMessage.cs#L14), we are reading `CorrelationId` from the  `TransportMessage`, we don't know if it was passed in or not.
I think this needs to be fixed at the transport level and a patch released for v3.3 version that addresses this.

**Comment by bording** [comment]
@johnsimons If the message doesn't have a CorrelationId, don't set the value at all, which will prevent the header from being added.

If the `TransportMessage.CorrelationId` property hasn't been set, then there won't be a header: https://github.com/Particular/NServiceBus/blob/5.2.18/src/NServiceBus.Core/TransportMessage.cs#L83

**Comment by bording** [comment]
Seems like making the change when the message is about to be sent makes more sense than when saving it. I know when I was talking to @boblangley about it, he was thinking about making a change here: https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Recoverability/Retries/RetryProcessor.cs#L174

**Comment by johnsimons** [comment]
Thanks @bording for the explanation

**Comment by andreasohlund** [comment]
We could check the headers collection instead of the property on the transport message?

**Comment by johnsimons** [comment]
It seems MSMQ always sets CorrelationId so there is always an empty header

**Comment by adamralph** [comment]
If we're considering the behaviour of multiple transports, would this discussion be better placed in https://github.com/Particular/ServiceControl/issues/794 ?

**Comment by johnsimons** [comment]
I am handling this in ServiceControl

**Comment by WojcikMike** [comment]
We should keep in mind that using native intragration we can not guarantee that correlation id will be present

**Comment by bording** [comment]
@jenspettersson ServiceControl 1.24 is now out, and it includes a fix for this issue:

https://github.com/Particular/ServiceControl/releases/tag/1.24.0

https://github.com/Particular/ServiceControl/issues/794
