### ISSUE TITLE
Declare queues inside routing topologies for more flexibility in custom routing topologies

### ISSUE THREAD

**Issue by volak** [Particular/NServiceBus.RabbitMQ#248]
Here at this line https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/Administration/QueueCreator.cs#L38

Queues are being declared before routing topology is initialized.  I just started messing with rabbitmq-sharding https://github.com/rabbitmq/rabbitmq-sharding - one of the requirements to use is to not declare the main queue, it handles sharding instances of the queues across nodes.  Meaning that with the NSB transport like it is its not compatible with this plugin

Not sure if its a big deal to move queue declare into possible user-land or not - but thats up to you guys

---

### Plan of Attack
- [x] make changes - #263
- [x] add docs - https://github.com/Particular/docs.particular.net/pull/2247

**Comment by adamralph** [comment]
@volak thanks for raising this. I'll have to investigate a little before giving an opinion.

**Comment by volak** [comment]
All in all the IRoutingTopology extension is nice, but its very limited.  For instance we can't use any constructor arguments - which is a pretty big limitation if you need to do something fancy with other services for routing

**Comment by bording** [comment]
@volak Moving the `QueueDeclare` into the `IRoutingToplogy` implementations is something I've been contemplating recently. However, since that would be a behavior break for any existing implementations, we'd need to release a new major version to be able to make that change, so it's not something we can do immediately.

**Comment by bording** [comment]
>All in all the IRoutingTopology extension is nice, but its very limited. For instance we can't use any constructor arguments - which is a pretty big limitation if you need to do something fancy with other services for routing

@volak Take a look at #250 and let me know if that fixes up things regarding `IRoutingTopology` limitations.

**Comment by volak** [comment]
@bording Looks good!

**Comment by adamralph** [comment]
@volak to what degree does NServiceBus.RabbitMQ 4.1.0 (containing #250) address your concerns?

**Comment by adamralph** [comment]
@volak after some discussion, we decided that the original idea you raised has merit regardless of the change we've already made to allow non-default constructors (#250).

We're now treating this as a feature which we would like to implement. Currently we believe it will have to be a breaking change so will require a major version bump, but we're investigating ways in which we can avoid the breakage and deprecate instead, which would allow a minor version bump. If the latter is possible, then the feature will probably be delivered sooner.

**Comment by volak** [comment]
@adamralph Thanks for the update! Looking forward to it, currently I'm running with a custom build of the transport during development.  #250 helps with a separate issue but the main queue non-declaring is the bigger problem forcing me to use a custom build.

**Comment by adamralph** [comment]
@volak FYI I'm going to spike this change with aim of making it non-breaking. /cc @Particular/rabbitmq-transport-maintainers 

BTW - is your custom build pushed to your fork somewhere?

**Comment by volak** [comment]
@adamralph Sure - I have a fork with the changes here: https://github.com/volak/NServiceBus.RabbitMQNext/tree/vanilla

but I didn't worry about compatibility and just commented out the QueueDeclare and added it to routing topology.

In this branch I actually also changed MessagePump to operate on a single connection to RabbitMq because each endpoint spinning up 5+ connections was causing disconnects when I started 10 instances of the endpoint (too many connections at once)
That change is in the branch but not referenced in my bug because its not as big of deal.

**Comment by bording** [comment]
>In this branch I actually also changed MessagePump to operate on a single connection to RabbitMq because each endpoint spinning up 5+ connections was causing disconnects when I started 10 instances of the endpoint (too many connections at once)

I'm curious about the behavior you were seeing that led to you making this change, because something sounds wrong here. I've had hundreds of simultaneous connections to a broker before, and everything works fine. RabbitMQ should be able to handle thousands of connections (or more with some configuration tweaks) without a problem.

**Comment by volak** [comment]
@bording Its not that big of a deal - but what I'm doing is I'm running NSB inside the new windows server 2016 docker feature.  So in the production-like environment when I deploy docker is starting 50-60 instances - each starting 5+ connections to a single server within a minute or so.  
It could be more a linux vs rabbit problem - but when checking the log files after a deployment there would always be 2-3 docker instances that crashed because they did not get a response from rabbit fast enough.

After some research and tuning from https://www.rabbitmq.com/networking.html I found a post online that rabbit recommends 2 connections, 1 for receiving and 1 for sending.  Because of erlang and blocking queues when memory alarm goes off and some such.  When I was working on the RabbitMqNext transport the connection issue became glaring because internally they start 2 real threads per connection and while debugging / coding I found it really easy to change from 5 connections with 1 channel each to 1 connection with 5 channels and did that.

Working back and forth between RabbitMqNext and this I just migrated the change and haven't had any rabbit connection issues since.

**Comment by adamralph** [comment]
I've started working in the spike. As a first step, see https://github.com/Particular/NServiceBus.RabbitMQ/pull/256

**Comment by adamralph** [comment]
Non-breaking spike is at #257.

Regardless of which (if any) method we choose, one thing to take into consideration is whether it's sufficient to pass both the receiving and sending addresses in a single list, or whether is something ultra-exotic that a custom routing topology needs to do which requires treating receiving addresses differently from sending addresses .

**Comment by adamralph** [comment]
After discussion with @Particular/rabbitmq-transport-maintainers we decided on a third approach, which adds a new interface with a single method which accepts all the queue addresses. Any custom routing topology which also implements this interface will have that method called instead of `IRoutingTopology.Initialize(IModel, string)`. Spike PRs closed and implementation PR raised: #263

**Comment by adamralph** [comment]
@Particular/rabbitmq-transport-maintainers regarding https://github.com/Particular/NServiceBus.RabbitMQ/issues/248#issuecomment-259950783 can we say with 100% certainty that a custom routing topology will *never* need to distinguish between sending and receiving queues? If not, I suggest we separate them into two parameters as a hedge against having to make a breaking change in the future.

**Comment by adamralph** [comment]
Note that we need to complete https://github.com/Particular/docs.particular.net/pull/2247 as part of this.

**Comment by bording** [comment]
@adamralph Regarding the one or two parameters question, take a look at https://github.com/Particular/NServiceBus/issues/4151. There's already talk in trying to rename these to be closer to what they're actually used for, so if we did implement two parameters, at the very least we might have to change the names of what we call our parameters to match in the future.

**Comment by adamralph** [comment]
@bording that's certainly worth considering, although that will be a breaking change in core, and I don't imagine that 7.0 will be released any time soon. I think it may better to reflect the current naming in core for now, and raise another issue (breaking) to align with core if/when that rename happens over there.

It seems like we can't say for sure that a topology will never need these queues separately and it's trivial to pass them separately vs together, so I think we should pass them separately. I'll add another commit to the PR which does that.

**Comment by adamralph** [comment]
Rather than raise a new issue for changing the parameter names later, I made a note in https://github.com/Particular/NServiceBus.RabbitMQ/issues/265

**Comment by adamralph** [comment]
As I started to [write the docs](https://github.com/Particular/docs.particular.net/pull/2247/files) for this, a fresh doubt arose in my mind.

In https://docs.particular.net/nservicebus/rabbitmq/routing-topology, we say

> If the above routing topologies aren't flexible enough, it is possible to take full control over routing by implementing a custom routing topology.

The key phrase here is *full control*. Through the implementation of this feature (the new `IDeclareQueues` interface), and the proposals for later collapsing the new interface into `IRoutingTopology`, we are effectively giving custom routing topologies *more control*. Following this logic leads to two possible outcomes:

-  The current docs are not accurate, since the current API does not in fact offer "full control over routing".
- The creation of queues sits outside "routing" and the responsibilities of a "routing topology".

If the former is true, then we just need to fix the docs. If the latter is true, then we need to rethink our implementation of this feature.

**Comment by bording** [comment]
How are we giving them more control than our own topologies? The custom topology doesn't have capability that we don't also have for our own internal topology. I'm not seeing a problem here at all.

**Comment by adamralph** [comment]
Added to the 4.2.0 milestone since the code changes are in, and only the docs are outstanding.

@bording discussed my [concern above](https://github.com/Particular/NServiceBus.RabbitMQ/issues/248#issuecomment-261325459) and we decided that it will be resolved via the docs update for this issue.
