### ISSUE TITLE
Allow passing of X509Certificates

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#252]
_from https://ddd-cqrs-es.slack.com/archives/random/p1476894400005161_

``` C#
namespace RabbitMQ.Client
{
    public class SslOption
    {
        public X509CertificateCollection Certs { get; set; }
    }
}
```

Using ☝️ we should be able to allow the user to pass in certificates, which we then hand off to the client.

**Comment by adamralph** [comment]
Reopening, since we need to add docs for this.

**Comment by adamralph** [comment]
Reminder that we need to add docs for this before we can release 4.3.0.

**Comment by adamralph** [comment]
Discussed in @Particular/rabbitmq-transport-maintainers sync. We will create a WIP PR in docs using a locally built package. We will close this issue after the PR content has been completed. (It will have to stay unmerged until the stable version is released.)

**Comment by bording** [comment]
Docs PR raised: https://github.com/Particular/docs.particular.net/pull/2366
