### ISSUE TITLE
Native message without message id or headers fails to get moved to error queue

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.RabbitMQ#258]
When the transport receives a native message without a message id, it considers it a poison message and attempts to move it to the error queue. The `RawSendInCaseOfFailure` call fails with a `NullReferenceException`, so this results in an endless loop instead.

The `NullReferenceException` happens if the native message also has no headers, so the Headers collection is null.

**Comment by bording** [comment]
@Particular/rabbitmq-transport-maintainers 

#259 Fixes this in develop. What sort of releases are we going to need for this? Can we just wait for next release, or do we need to do a 4.0.1/4.1.1 set of releases?

**Comment by WojcikMike** [comment]
@bording We have this 'feature' ready: https://github.com/Particular/NServiceBus.RabbitMQ/issues/202 so we can release it with this

**Comment by adamralph** [comment]
I've merged #259, since the change is good, but I'm not 100% sure if it fixes this bug.

The description says:

> When the transport receives a native message without a message id, it considers it a poison message and attempts to move it to the error queue. The RawSendInCaseOfFailure call fails with a NullReferenceException, so this results in an endless loop instead.

and then goes on to say:

> The NullReferenceException happens if the native message also has no headers, so the Headers collection is null.

It seems like #259 fixes the second problem (null headers collection), but it doesn't seem to fix the first problem (missing message ID), or am I missing something?

**Comment by bording** [comment]
> It seems like #259 fixes the second problem (null headers collection), but it doesn't seem to fix the first problem (missing message ID), or am I missing something?

A missing message id isn't the bug, that's already handled by https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/Receiving/MessageConverter.cs#L59

If a message comes in without a message id, it's supposed to treat it as a poison message and forward it to the error queue. The bug is that if that message also has no headers (meaning that the `Headers` collection on the `BasicProperties` instance will be null instead of an empty collection like it arguably should be), then the move to the error queue fails by throwing a `NullReferenceException`. The message pump will catch the error and reject and requeue the currently being processed message.

So, instead of detecting the message as poison and moving it to the error queue, the message pump will get stuck in an endless loop of trying to process this message.

The change in #259 will prevent the `NullReferenceException` from being thrown, breaking the loop.

**Comment by adamralph** [comment]
Fixed in #259.
