### ISSUE TITLE
Poison messages ack-ed and not forwarded to the error queue

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.RabbitMQ#283]
## Description
In version 3 of the transport whenever headers for a message being received cannot be properly [deserialized](https://github.com/Particular/NServiceBus.RabbitMQ/blob/3.5.0/src/NServiceBus.RabbitMQ/RabbitMqDequeueStrategy.cs#L195) it gets ack-ed on the broker and not moved to the `error` queue.

I'm not sure what are the scenarios in which the header deserialization can fail but that could potentially lead to message loss.

**Comment by adamralph** [comment]
Thanks for raising @tmasternak. FYI @bording is going to spike a potential fix for this.

**Comment by adamralph** [comment]
For the 3.1.1, 3.2.1, 3.3.4 and 3.4.1 backports, do we need to title and label each PR as a bug, on each appropriate milestone?

**Comment by adamralph** [comment]
I updated the description of this issue to add some more context.
