### ISSUE TITLE
Remove the package dependency on RabbitMQ.Client

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#315]
... by merging the assembly into ours, using either ILMerge or ILRepack.

We currently have 9 supported versions of NServiceBus.RabbitMQ which is by far the most number of supported versions of any of the NServiceBus* packages. Most of these releases were driven by breaking changes in RabbitMQ.Client being released in patch or minor versions. If we merge the client into our assembly then we remove the necessity to release when one of these breaking changes is made, and we can instead *choose* to update the version if/when we want to take advantage of a bug fix or new feature in a new version.

**Comment by WojcikMike** [comment]
@adamralph what are the implication for a "hybrid" clients. The ones that use NSB + native RabbitMQ api. Will they have to add RabbitMQ client as a reference so that they can use it? I don't know how common scenario this is actually.

**Comment by adamralph** [comment]
@WojcikMike that is only an issue if we expose RabbitMQ.Client types through our public API. In that case, we are indeed in integration package between NServiceBus and RabbitMQ.Client. If, however, we don't expose any RabbitMQ.Client types via our public API, then we are an integration package between NServiceBus and the RabbitMQ broker, with RabbitMQ.Client as an internal implementation detail, and a consuming app can still separately reference any version of RabbitMQ.Client it wants to.

**Comment by WojcikMike** [comment]
Thanks you for making it clear.

**Comment by bording** [comment]
We do directly expose RabbitMQ.Client types in our public API.

Looking at `APIApprovals.Approve.approved.txt` here's where we are using types from RabbitMQ.Client:

- `RabbitMQTransportSettingsExtensions.CustomMessageIdStrategy`
- `IDeclareQueues.DeclareAndInitialize`
- Every method in  `IRoutingTopology`

So based on that alone, I don't think we can internalize the client.

**Comment by adamralph** [comment]
Is it worth investigating the removal of those types from our public API, regardless of whether we internalise the client? (Obviously that would have to be a major version bump.)

**Comment by bording** [comment]
I'm not sure it really makes sense to given how they are used. For example, the entire point of the `CustomMessageIdStrategy` is to provide the end user a way to configure how to look for a message id from the native message, so it would be strange to then hand them something that wasn't the actual incoming native message data (`BasicDeliverEventArgs`).

I'd also want to be careful to not introduce more allocations into the message processing paths, which seems like we'd end up doing if we have to create some sort of wrapping classes for everything.

**Comment by adamralph** [comment]
Discussed in @Particular/rabbitmq-transport-maintainers sync and concluded that this isn't possible, largely due to the `IRoutingTopology` interface.
