### ISSUE TITLE
Add warning to docs about disabling publisher confirms with the conventional routing topology

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#327]
As detailed in https://github.com/Particular/NServiceBus.RabbitMQ/issues/135, when publisher confirms are disabled, and the conventional routing topology is used, message loss can occur. There is no good way to fix this without violating our principles of queue ownership in the context of RabbitMQ (sender owns it's queues, receiver owns it's queues), which could lead to difficult to diagnose problems in production. E.g. a sender could create a queue on behalf of a receiver with different settings than the receiver requires, and when the receiver tries to create it's queue, it suffers catastrophic failure.

Publisher confirms are enabled by default. Disabling publisher confirms should be viewed as a performance option, which comes at the cost of some possible message loss. This should be clearly documented.

**Comment by ramonsmits** [comment]
https://github.com/Particular/docs.particular.net/pull/4922
