### ISSUE TITLE
4.3.0 release

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#347]
- [x] Merge https://github.com/Particular/docs.particular.net/pull/2366
- [x] Merge https://github.com/Particular/docs.particular.net/pull/2451 (@adamralph to review)
- [x] Close remaining issues on the 4.3.0 milestone
- [x] Create a `release-4.3.0` branch
- [x] RC testing - ends on 5th April (1 week to get any response, total max 2 weeks for RC testing)
  - [x] Push package to NuGet gallery - 14th March
  - [x] Ask TAMs if they have customers on NSB v6 and RabbitMQ that would be interested in RC testing - 22nd March
  - [x] Announce on Google Groups - 14th March https://groups.google.com/forum/#!topic/particularsoftware/2jIqiGx0zRc
- [x] Follow regular release procedure
- [x] Notify affected customers

**Comment by SeanFeldman** [comment]
Notify affected customers

**Comment by adamralph** [comment]
Given that "labeled as rc" has been added to the PoA, shouldn't all instances of "beta" be changed to "RC"?

**Comment by adamralph** [comment]
👍  thanks @SeanFeldman 

BTW what is the purpose of this comment?

> Notify affected customers

**Comment by SeanFeldman** [comment]
A reminder. Customers affected by this issue that requested to be notified about the final bits going out.

**Comment by adamralph** [comment]
@SeanFeldman OK, I've added it to the PoA, so it's a first class item.

**Comment by adamralph** [comment]
All issues on the 4.3.0 milestone are now closed, so let's 🚢 that RC!

FYI I created the `release-4.3.0` branch and protected it. That means an RC package has been produced in CI.

BTW - why are we only publishing the RC to MyGet and not NuGet?

**Comment by adamralph** [comment]
FYI I changed "MyGet" to "NuGet gallery" in the PoA and checked off the package push and GG announcement. /cc @Particular/rabbitmq-transport-maintainers @SeanFeldman

**Comment by adamralph** [comment]
Added dates to those last two points.

**Comment by WojcikMike** [comment]
At the moment the package was downloaded 185 times (data from [nuget](https://www.nuget.org/packages/NServiceBus.RabbitMQ/4.3.0-rc0001)), 

I checked docs repo and there is not feedback related to Rabbit.

**Comment by SeanFeldman** [comment]
Notified the affected customer (planning to upgrade shortly).

**Comment by bording** [comment]
4.3.0 is now on NuGet and the GG announcement has been posted.

I'm going to go ahead and close this as being done!
