### ISSUE TITLE
Allow disabling of the timeout manager

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus.RabbitMQ#350]
Allow disabling of the timeout manager when only native delays are being used. That would allow us to skip the configuration of persistence for timeouts, and to save resources by not needing timeout queues and a process to read from those queues.

**Comment by SeanFeldman** [comment]
Fixed by https://github.com/Particular/NServiceBus.RabbitMQ/commit/0d887804045aa8c731587e402bbe39a376a0ed12

**Comment by SeanFeldman** [comment]
Closed by #329
