### ISSUE TITLE
Send performace optimization when all endpoints use native delays

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus.RabbitMQ#351]
When delaying a message within a system that uses only native delays, the senders do not have to create bindings between the delay infrastructure and destination queue as this binding is created by the receiver.  That could lead to a performance increase when sending delayed messages.

**Comment by SeanFeldman** [comment]
Fixed by https://github.com/Particular/NServiceBus.RabbitMQ/commit/0d887804045aa8c731587e402bbe39a376a0ed12

**Comment by SeanFeldman** [comment]
Closed by #329
