### ISSUE TITLE
Find the latest version of the broker on which Rabbit transport works

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus.RabbitMQ#365]
As a step towards documenting supported version of Rabbit broker, we should start with finding the latest version on which the Rabbit transport works. Later on, we will make sure that this check is verified with the release of the next version.

**Comment by WojcikMike** [comment]
The first test performed on the: 
 - [ ] RabbitMQ 3.6.6 Erlang 18 - local machine
 - [ ] RabbitMQ 3.4.4, Erlang 17.4 - using docker

The tests involved running acceptance tests

**Comment by WojcikMike** [comment]
The next tests happened using docker on version: 
 - RabbitMQ 3.3.5, Erlang 17

And it failed with a message:
RabbitMQ.Client.Exceptions.OperationInterruptedException : The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text="PRECONDITION_FAILED - invalid arg 'x-message-ttl' for queue 'nsb.delay-level-27' in vhost '/': {value_too_big,134217728000}", classId=50, methodId=10,

**Comment by WojcikMike** [comment]
I will verify that our tests pass for version 3.4.0 to have the largest major that we support.

**Comment by SeanFeldman** [comment]
> I will verify that our tests pass for version 3.4.0 to have the largest major that we support.
@WojcikMike did you mean "minor"?

**Comment by WojcikMike** [comment]
> @WojcikMike did you mean "minor"?
Yes :) I meant minor

**Comment by WojcikMike** [comment]
At the moment I was unable to install Rabbit server version 3.4.0 on my box, neither did I found a docker image with that exact version. (All 3.4 versions were updated to 3.4.4).

**Comment by adamralph** [comment]
@WojcikMike were you unable to install 3.4.0 from here: https://www.rabbitmq.com/releases/rabbitmq-server/ ?

**Comment by WojcikMike** [comment]
Yep, i installed it and tried with few versions of erlang. But It never started. I tried few things with now success.

**Comment by bording** [comment]
I've installed 3.4.0 with Erlang 16 and confirmed that it works.

We can go ahead and document that is our minimum required version.

**Comment by adamralph** [comment]
👍 great, thanks @bording

**Comment by adamralph** [comment]
Now I'm wondering if we shouldn't somehow bake this into CI.

**Comment by WojcikMike** [comment]
@adamralph we could do it very easily using docker containers. We can discuss it on the call

**Comment by adamralph** [comment]
We decided to document that the earliest version tested successfully is 3.4.0 and leave it at that.
