### ISSUE TITLE
Add a setting to disable server TLS certificate validation checks

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.RabbitMQ#380]
Per https://github.com/Particular/NServiceBus/issues/4705, the RabbitMQ client does support a way to disable server certificate validation checks when connecting via TLS, but we don't offer a way to configure it.

Is this something we should support?

## Plan of attack

- [x] make changes - #430
- [x] update docs - https://github.com/Particular/docs.particular.net/pull/3218

**Comment by adamralph** [comment]
I'm not opposed to it, if the use case mentioned there is valid, and this will unblock it.

**Comment by bording** [comment]
This will be in the 4.4.0 release.

**Comment by bording** [comment]
@AnatoliiAPFM 4.4.0 has been released and here is the documentation on the new setting that disables remote certificate validation: https://docs.particular.net/transports/rabbitmq/connection-settings#transport-layer-security-support-remote-certificate-validation
