### ISSUE TITLE
KeyNotFoundException with SettingsKeys.RoutingTopologySupportsDelayedDelivery

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.RabbitMQ#394]
This is not really an issue I just wanted to point it out. I'm totally OK if this gets closed as won't fix because the scenario I'll describe probably won't happen usually.

I tried out ServiceFabric routing sample with RabbitMQ. The samples has AzureServiceBus adapter installed. I left all the packages there and switched to RabbitMQ but forgot to change one endpoint. The endpoint was still using 

```
endpointConfiguration.UseTransport<AzureServiceBusTransport>()
```

but suddenly started throwing with a `KeyNotFoundException` coming from [`PreventRoutingMessagesToTimeoutManager`](https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.Transport.RabbitMQ/DelayedDelivery/PreventRoutingMessagesToTimeoutManager.cs#L16) because the feature is enabled by default and detected by scanning.

I can imagine the only scenario where this could come up is when people are doing demos and fiddle around with multiple broker based transports such as I did with ASB and Rabbit.

**Comment by WojcikMike** [comment]
@Particular/rabbitmq-transport-maintainers isn't it similar to https://github.com/Particular/NServiceBus.RabbitMQ/pull/393 ?

**Comment by bording** [comment]
@WojcikMike Yeah, this would be happening because of the feature being enabled by default, so the outcome of #393 will determine if we make a change that prevents this or not.

**Comment by bording** [comment]
Given that this is a rare scenario, and can be solved by excluding assemblies from scanning, I don't see anything that needs to be changed here.
