### ISSUE TITLE
Update doco and samples for ConnectionStringName

### ISSUE THREAD

**Issue by dbelcham** [Particular/NServiceBus.RabbitMQ#416]
v7 of NServiceBus Core has deprecated the use of `ConnectionStringName`. Docs, snippets and samples will need to be updated to remove the use of this capability. More info on what the alternative is can be found in https://docs.particular.net/nservicebus/upgrades/6to7/ once https://github.com/Particular/docs.particular.net/pull/3126 has been merged.

**Comment by bording** [comment]
PR opened: https://github.com/Particular/docs.particular.net/pull/3256

**Comment by bording** [comment]
PR merged
