### ISSUE TITLE
Use durable exchanges and queues by default when using non-durable messages

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#439]
Relates to #167

## Solution

- Remove the throwing of an exception when `DisableDurableMessages()` is called but `UseDurableExchangesAndQueues(bool)` is not, and use durable exchanges and queues in that case
- Deprecate `UseDurableExchangesAndQueues(bool)` with an error
- Introduce a new `DisableDurableExchangesAndQueues()`

## Plan of attack

- [ ] Make changes
- [ ] Update docs

**Comment by ramonsmits** [comment]
Can it be prevented to be introduced in a major? Introduction of `DisableDurableExchangesAndQueues` seems non-breaking and opt-in to new behavior.
