### ISSUE TITLE
Add support for using SSL when connecting to the broker

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#44]
https://www.rabbitmq.com/ssl.html

**Comment by rafsojka** [comment]
+1
Can I kindly ask if this going to be released any time soon or I should get my hands dirty and implement IManageRabbitMqConnections with SSL in my project for now?

**Comment by andreasohlund** [comment]
@rafsojka this one is a duplicate of https://github.com/Particular/NServiceBus.RabbitMQ/issues/82

If you need this in the near future I'd suggest you use IManageRabbitMqConnections or perhaps get a pull request going. Ping me if you need so help to get started. Closing this one
