### ISSUE TITLE
Add possibility to subscribe to blocked/unblocked connection events

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus.RabbitMQ#450]
Rabbit client library provides 2 events that are triggered when a connection is blocked/unblocked (due to limited resources on the broker, more details here: https://www.rabbitmq.com/connection-blocked.html). Those events are exposed on a connection object. At the moment using Rabbit transport, there is no way to handle those events.

**Comment by bording** [comment]
As of version 5.1.0, we are now logging when these events happen: #468

**Comment by ramonsmits** [comment]
@bording Seems this can be closed?

**Comment by bording** [comment]
In 5.1.0 we hooked up logging code to the events mentioned, but in theory we could expose those events via an API to let users add code to them.

I'm not sure I see the value of that at this point, though. I'm not really sure what other code would be useful in there other than logging.

Based on that, yeah it seems like we could say that logging was enough and close this.
