### ISSUE TITLE
Problem registering publisher

### ISSUE THREAD

**Issue by imperugo** [Particular/NServiceBus.RabbitMQ#474]
Hi, 
I'm trying NSB7 (7.0.0-rc0001) with RabbitMq (5.0.0-rc0001) and, looking the documentation [here](https://docs.particular.net/nservicebus/upgrades/6to7/) I should register my event routing in this way:

```csharp
var transport = endpointConfiguration.UseTransport<MyTransport>();

var routing = transport.Routing();
routing.RegisterPublisher(
    assembly: typeof(OrderAccepted).Assembly,
    publisherEndpoint: "Sales");

routing.RegisterPublisher(
    assembly: typeof(OrderAccepted).Assembly,
    @namespace: "PriorityMessages",
    publisherEndpoint: "Preferred");

routing.RegisterPublisher(
    eventType: typeof(OrderSent),
    publisherEndpoint: "Sending");
```

Unfortunately this is not possible with *RabbitMqTransport* because It doesn't implement `IMessageDrivenSubscriptionTransport` that is needed by the Extension method

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptionsConfigExtensions.cs#L42

Any hint how to solve this? PR?

**Comment by bording** [comment]
The RabbitMQ transport supports pub/sub natively. Registering publishers is only required for message-based pub/sub, so that’s why the RabbitMQ transport doesn’t have those APIs. You don’t need them!

**Comment by imperugo** [comment]
ok. 
Thanks for the info
