### ISSUE TITLE
Removing lazy attribute from delayed infrastructure can increase throughput

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus.RabbitMQ#479]
## Problem statement
Native delays for Rabbit transport uses [lazy queues](https://www.rabbitmq.com/lazy-queues.html). By removing this setting for queues representing low delays we could remove this setting to increase performance and remove some I/O pressure. 

## Value
A benefit could be seen in systems that uses a lot of delayed messages by decreasing I/O usage, and potentially increasing thorughput of delayed messages.

The specific potential gains would have to be measured before evaluating this issue.

This idea was raised by a customer.

**Comment by bording** [comment]
I would definitely want to see specific measurements before making a change here. Without lazy queues, you're going to potentially run into memory pressure issues because the broker will try to keep messages in memory, and then will have to pause to page them out to disk. Using lazy queues is often a performance increase, not a decrease, which is why we made them lazy in the first place.

**Comment by WojcikMike** [comment]
@bording I agree with what you said, 2 clarifications that could be written in a more clear way in the issue:
a. This idea is only for queues that represent small delays (1s, 2s), for which the messages stay for rather a small period of time before being moved further
b. Yeah it needs to be measured, as for now, the discussion is theoretical.

Overall it is a tradeoff between IO vs RAM and a risk of pausing the broker due to out of memory issues. If you have sufficient amounts of RAM there is no benefit in lazy queues, unless I misunderstood something while reading the doco.

**Comment by bording** [comment]
The thing to keep in mind here is that we're using persistent queues. That means every single message has to be written to disk anyway, so the per-message disk IO is always going to happen. A non-lazy queue then also has to keep a copy of the message in memory, which can then need to be paged out, causing additional disk IO.

A lazy queue simplifies things by only writing it to disk, so I would suspect it to be almost entirely a performance win when dealing with persistent queues.

**Comment by Sudhakar85** [comment]
NserviceBus RabbitMQTransport doesn't have option to create lazy queue even though native supports lazy queue creation. If found sometime to research on this but no direction. Do you guys know ?

**Comment by bording** [comment]
@Sudhakar85 Please see my answer to the issue raised about this: https://github.com/Particular/NServiceBus.RabbitMQ/issues/500#issuecomment-426124446
