### ISSUE TITLE
Endpoint getting stuck with "System.Exception: Failed to add " in the logs

### ISSUE THREAD

**Issue by dasjestyr** [Particular/NServiceBus.RabbitMQ#484]
## Problem
I'm having an issue that is causing all of my services to halt and no longer process messages. I'm not seeing any application errors, but in the logs of a couple different services (consumers), I'm getting logs like this:

> System.Exception: Failed to add 3 at NServiceBus.Transport.RabbitMQ.ConfirmsAwareChannel.GetConfirmationTask() at NServiceBus.Transport.RabbitMQ.ConfirmsAwareChannel.SendMessage(String address, OutgoingMessage message, IBasicProperties properties) at NServiceBus.Transport.RabbitMQ.MessageDispatcher.SendMessage(UnicastTransportOperation transportOperation, ConfirmsAwareChannel channel) at NServiceBus.Transport.RabbitMQ.MessageDispatcher.Dispatch(TransportOperations outgoingMessages, TransportTransaction transaction, ContextBag context) at NServiceBus.DelayedRetryExecutor.Retry(IncomingMessage message, TimeSpan delay, TransportTransaction transportTransaction) at NServiceBus.RecoverabilityExecutor.DeferMessage(DelayedRetry action, ErrorContext errorContext) at NServiceBus.Transport.RabbitMQ.MessagePump.Process(BasicDeliverEventArgs message) at NServiceBus.Transport.RabbitMQ.MessagePump.Consumer_Received(Object sender, BasicDeliverEventArgs eventArgs)

> System.Exception: Failed to add 2 at NServiceBus.Transport.RabbitMQ.ConfirmsAwareChannel.GetConfirmationTask() at NServiceBus.Transport.RabbitMQ.ConfirmsAwareChannel.SendMessage(String address, OutgoingMessage message, IBasicProperties properties) at NServiceBus.Transport.RabbitMQ.MessageDispatcher.SendMessage(UnicastTransportOperation transportOperation, ConfirmsAwareChannel channel) at NServiceBus.Transport.RabbitMQ.MessageDispatcher.Dispatch(TransportOperations outgoingMessages, TransportTransaction transaction, ContextBag context) at NServiceBus.ForkExtensions.Fork[TFromContext,TToContext,TForkContext](IForkConnector`3 forkConnector, TForkContext context) at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.Invoke(ITransportReceiveContext context, Func`2 next) at NServiceBus.MainPipelineExecutor.Invoke(MessageContext messageContext) at NServiceBus.Transport.RabbitMQ.MessagePump.Process(BasicDeliverEventArgs message)

What I'm seeing in RMQ management panel is: Ready=0, Unacked=3, Total=3 and the like. So it appears to be unable to ack messages or fail them.

I'm not sure what the problem actually is or how to correct it, but in the meanwhile, all services are stuck in a loop that continues to output those exceptions.

## Plan of action
  * Patch 5.0.1 - [PR](https://github.com/Particular/NServiceBus.RabbitMQ/pull/495)
  * Patch 4.2.2 - [PR](https://github.com/Particular/NServiceBus.RabbitMQ/pull/496)
  * Release patches

## Patches
 * [5.0.1 - TODO]()
 * [4.2.2 - TODO]()

**Comment by WojcikMike** [comment]
Hi @dasjestyr ,

Would you mind sending us a [support case](https://particular.net/support) with this? I would love to learn about your setup to try to find a cause for that but I don't want this information to be shared via github issue.

**Comment by dasjestyr** [comment]
I was able to un-stuck it by tearing down the services completely. I think kubernetes was spinning them back up so fast that rabbit didn't get a chance to drop the unacked messages. Once, I tore them down, the messages got moved back into ready and I was able to restart. 

I guess the only thing left is to understand how that could have happened so that I can avoid it in the future. Do you still want me to open the case? I think our setup is pretty textbook.

**Comment by WojcikMike** [comment]
@dasjestyr yes, please. I prefer to be on the safe side and gather as much information as I can than to dismiss it. Especially that at the moment we have only a few examples of this error happening.

**Comment by tmasternak** [comment]
@dasjestyr the logs that you have included are showing failures for executing retries. Would it be possible for you to share the logs for the exception that caused the retries in the first place?

**Comment by dasjestyr** [comment]
@tmasternak unfortunately, those logs are gone. They never made it out to Loggly and those that went to console were killed when the container restarted. When I was working the problem, believe it was a legit problem in the app code that caused a requeue/nack. I would love to recreate this for you, but I have no idea how.

If I remember correctly, I believe the problem occured when we pushed the updated container. The service started up and tried to begin processing the queue and immediately started throwing this error. It is possible that one of us tried to purge the queue while there were still messages in "Not Acked".

**Comment by tmasternak** [comment]
@dasjestyr the patched version of the transport is available on NuGet.

**Comment by dasjestyr** [comment]
Thanks!
