### ISSUE TITLE
Order of settings

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.RabbitMQ#50]
Values provided by users in ConfigSection should take precedence over values provided with Fluent API, while Fluent API overrides default values set by ConfigSeaction.

ConfigSection defaults --> Fluent API --> CofnigSection user values

**Comment by andreasohlund** [comment]
Don't think this one is correct. Fluent api should always win over any config

**Comment by SeanFeldman** [comment]
Sorry @andreasohlund, I used a wrong repo. This is a duplicate from [core](https://github.com/Particular/NServiceBus/issues/2538). I will need to verify this behaviour with Azure transports.
