### ISSUE TITLE
Lazy Queue - RabbitMQ support

### ISSUE THREAD

**Issue by Sudhakar85** [Particular/NServiceBus.RabbitMQ#500]
RabbitMQ has option to create the Queue Lazy by using the parameter "x-queue-mode:Lazy" . Is this feature available or any plan to implement in future ?

**Comment by bording** [comment]
We don't have plans to have the queus we create be set that way by default, but you can control that yourself by setting a policy on the broker. Seeing the "Using a policy" setting on https://www.rabbitmq.com/lazy-queues.html.


That gives you much more control than anything we could do.

**Comment by Sudhakar85** [comment]
Thanks for the quick response. !!
