### ISSUE TITLE
Enable the cleanup of RabbitMQ resources on shutdown

### ISSUE THREAD

**Issue by mattes337** [Particular/NServiceBus.RabbitMQ#504]
I am currently writing a custom routing topology for my application which works just fine with the current means. I would however like to remove a binding to a queue upon application shutdown. But since the shutdown is not propagated to the topology I cannot.

Wouldn't it make sense to add a Shutdown method to the IRoutingTopology-Interface and call it upon shutdown? I know that it won't be called in case of critical failures but that is fine for me.

**Comment by bording** [comment]
Our concept of routing topologies aren't intended to alter things when an endpoint isn't running. If that happened, then you'd experience message loss.

Can you explain a bit more about how your custom routing topology works that it would need to alter bindings like that at shutdown?

**Comment by bording** [comment]
Would it be possible to model those messages as events? If so, then you can unsubscribe from them when the endpoint shuts down.

**Comment by mattes337** [comment]
Yes they are already events, so this is an option. How would I hook-in the shutdown routine though?

**Comment by bording** [comment]
You shouldn't need to do that, you can just call the existing `Unsubscribe` API on `IEndpointInstance`.

**Comment by bording** [comment]
In other words, you should be able to achieve this without needing to implement a custom routing topology at all.

**Comment by mattes337** [comment]
No no, the topology is required for other purposes. Thanks for the hint, I'll try to use the Unsuscribe call.

**Comment by bording** [comment]
@mattes337 I'm going to go ahead and close this issue. Please re-open it if you think there's something else we should consider here.
