### ISSUE TITLE
Are the RabbitMqDequeueStrategy/* settings removed in newer versions?

### ISSUE THREAD

**Issue by TraGicCode** [Particular/NServiceBus.RabbitMQ#519]
I noticed one of our applications is utilizing the following NserviceBus.RabbitMQ Specific settings in the app.config.  I cannot find any information from the documentation on the settings so i'm curious as to if they were removed and if so in what version.

```
    <add key="NServiceBus/RabbitMqDequeueStrategy/TimeToWaitBeforeTriggering" value="02:00:00" />
    <add key="NServiceBus/RabbitMqDequeueStrategy/DelayAfterFailure" value="00:00:05" />
```

Thanks!

**Comment by bording** [comment]
Take a look at the upgrade guide : https://docs.particular.net/transports/upgrades/rabbitmq-3to4#controlling-behavior-when-the-broker-connection-is-lost

It mentions that the XML configuration options have been removed and talks about the replacements.
