### ISSUE TITLE
when an event was removed,the related  subscription is not unsubscribed automatically 

### ISSUE THREAD

**Issue by Varorbc** [Particular/NServiceBus.RabbitMQ#523]
When I used RabbitMQ Transport, I removed an event and I found that it would not unsubscribe.

**Comment by ramonsmits** [comment]
@Varorbc Subscriptions must be unsubscribed explicitly, is that how you unsubscribed?

See the following example:

- https://docs.particular.net/samples/manual-unsubscribe/

**Comment by Varorbc** [comment]
What you mean is that I need to manually unsubscribe before deleting this event class?

**Comment by bording** [comment]
> I first thought that when I delete this event class, the routing topology will help me automatically unbind in the exchanges on the RabbitMQ broker.

No, this does not happen. We only create things, we don't remove them. We don't have a reliable way to tell what should be removed, so anything we tried to clean up for you could in fact result in message loss instead.

**Comment by Varorbc** [comment]
@bording Is that what I need to manually unbind in the exchanges on the RabbitMQ broker?

**Comment by bording** [comment]
> @bording Is that what I need to manually unbind in the exchanges on the RabbitMQ broker?

I'm not sure what you're asking here.
