### ISSUE TITLE
Support multiple RabbitMQ node hostnames

### ISSUE THREAD

**Issue by AlanMacdonald** [Particular/NServiceBus.RabbitMQ#525]
The rabbitmq dotnet client project appears to support multiple hostnames in the ConnectionFactory class when calling CreateConnection.  NServiceBus doesn't utilise this functionality as far as I can tell, which means if using a RabbitMQ cluster we need a load balancer in front of it.  If NServiceBus supported a comma separated host list for connecting to with random host selection then it would probably suffice instead of needing a load balancer which would be easier.

**Comment by bording** [comment]
We actually used to expose this from the transport, but it was removed in 3.0.0. Take a look at https://groups.google.com/forum/#!topic/particularsoftware/8EkMRN97hVU/discussion to see more about why we decided to remove it.

> If NServiceBus supported a comma separated host list for connecting to with random host selection then it would probably suffice instead of needing a load balancer which would be easier.

At the time we removed the feature, the client didn't do any sort of random selection for the initial connection attempt. It only randomized and tried the other entries during the automatic connection recovery process. We weren't using the client's built-in connection recovery at the time (we do now), so I don't think we got any benefit from exposing the feature.

Looking at the client code now, it seems to indicate that it would now randomly select an entry even for the initial connection attempt, but I'm not actually sure it's implemented correctly. I'd need to study the code a bit more to be sure, but I believe it might still only use the randomization during the automatic connection recovery process.

**Comment by bennettfactor** [comment]
Hi, this would be useful for my use case, in which we would prefer to use client-defined config that is provided in the native C# RabbitMQ client.

**Comment by tmasternak** [comment]
Hi @bennettfactor that you for sharing your feedback. This will be considered when planning the next enhancement release.

**Comment by WilliamBZA** [comment]
Hi @bennettfactor, this will be included in the next major version of the transport. We're introducing support for Quorum queues via a `RabbitMQClusterTransport` which allows you to specify multiple nodes to connect to.
