### ISSUE TITLE
Allow consumer tag to be set

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#54]
This makes it easier to determine which instance of an endpoint is doing what when scaled out across machines.

Raised on the mailing list:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/KG2PzTQPV0w/OnVjJDmZxacJ

**Comment by andreasohlund** [comment]
@scottmeyer does this cover your needs?

**Comment by scottmeyer** [comment]
Yes, looks like this will cover our needs. Thanks
