### ISSUE TITLE
Support renaming the nsb.delay exchanges

### ISSUE THREAD

**Issue by mariusin79** [Particular/NServiceBus.RabbitMQ#550]
We are adding nservicebus support to a few services deployed to a company wide RabbitMq-cluster. We would like to use the native delay mechanism but we are running into some company policy issues since exchanges needs to be namespaced. It would be great if you changed this:

    static class DelayInfrastructure
    {
         ...
        public const string DeliveryExchange = "nsb.delay-delivery";
    }

To something configurable.

**Comment by DavidBoike** [comment]
Thanks @mariusin79! I've labeled this as a possible candidate for our enhancement release process.

**Comment by helenktsai** [comment]
Hi @mariusin79,

We are going through our RabbitMQ enhancement requests and wanted to follow up with you regarding this one. Is there still a need for this on your end?

**Comment by WilliamBZA** [comment]
@mariusin79 

Would being able to specify a prefix be sufficient?

**Comment by WilliamBZA** [comment]
Closing due to lack of feedback. If this is still important to you please reopen so that we can further discuss it with you.
