### ISSUE TITLE
Increase `RequestedHeartbeat` default from 5 to 60 seconds to align with the RabbitMQ default

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.RabbitMQ#551]
The current default of 5 seconds for [`RequestedHeartbeat`](https://docs.particular.net/transports/rabbitmq/connection-settings#connection-string-options-requestedheartbeat) results in 2.5 second heartbeat frame lengts. If 2 heartbeats are missed the client will shutdown. If the broker is busy it can happen that an endpoint instance shutsdown too fast when it cannot receive any heartbeat within 5 seconds.

RabbitMQ uses a default of 60 seconds as stated in their documentation:

> The timeout is in seconds, and default value is 60. Older releases used 580 seconds by default.

Source: https://www.rabbitmq.com/heartbeats.html

**Comment by bording** [comment]
I agree that this should be done. The question is when is it safe to make this change? This doesn't seem like it would be a breaking change, so it seems like we could just go ahead and do it.

**Comment by TraGicCode** [comment]
I agree this would be great to reduce noise.

**Comment by alaw-emoney** [comment]
We've encountered some unfortunate process failures that might have been mitigated if the client had a few more seconds to respond. We might end up going with 20 or 30 seconds, but it is definitely surprising that the default is 5 seconds. 10 seconds default would be a good start. I highly doubt any production system would have a new issue if the default was changed from 5 to 10 seconds.
