### ISSUE TITLE
Make the direct routing topology support multiple inheritance

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#56]
As mentioned in #11 we're doing a first or default which is non-deterministic if multiple inheritance is in play.

We need to figure out a way to support this scenario.

**Comment by adamralph** [comment]
Discussed this in the @Particular/rabbitmq-transport-maintainers sync today. This is something we can fix, but it would break wire compatibility.

One option put forward to is to create a completely new (opt-in) topology. In practice that would require a simultaneous switch to the new topology for all affected endpoints, plus a clear out of the exchanges from the old topology.

**Comment by adamralph** [comment]
Withdrawing, see https://github.com/Particular/NServiceBus.RabbitMQ/issues/11#issuecomment-260711710
