### ISSUE TITLE
Is it Possible Extract AMQP connection string from NServiceBus.RabbitMQ

### ISSUE THREAD

**Issue by TraGicCode** [Particular/NServiceBus.RabbitMQ#564]
Hello,

We currently have an asp.net core 3.0 application using NServiceBus and are wanting to utilize the follow healthcheck nuget package.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.RabbitMQ/RabbitMQHealthCheck.cs

Unfortunately, NServiceBus.RabbitMQ looks like it accepts a connection string ( which is in the format of a sql connection string ) instead of an AMQP connection string that rabbitmq expects ( https://www.rabbitmq.com/uri-spec.html ) and therefore we essentially either need to "massage" the NServiceBus RabbitMQ Connection string or have 2 connection strings in our appsettings.json

Is there any classes within NServiceBus.RabbitMQ that are part of the libraries public interface that we can use to convert the NserviceBus specific rabbitmq connection string to the mentioned AMQP connection string?

**Comment by bording** [comment]
> Is there any classes within NServiceBus.RabbitMQ that are part of the libraries public interface that we can use to convert the NserviceBus specific rabbitmq connection string to the mentioned AMQP connection string?

No, there is no way to do that.

**Comment by SeanFeldman** [comment]
After discussing this issue we'd like to slightly modify the suggestion in the following way:

1. Allow configuring the transport with a valid [RabbitMQ (client) connection string](https://www.rabbitmq.com/uri-spec.html).
1. Additional configurations that are NServiceBus transport specific to be exposed as configuration APIs.

@TraGicCode, this should work for your use-case as well. Would you agree with the suggestion?

**Comment by TraGicCode** [comment]
@SeanFeldman ,

Sounds great to me!

**Comment by SeanFeldman** [comment]
@TraGicCode we're moving forward with this and will release as part of the upcoming enhancement release. It will be possible to use an AMQP connection string and set the rest of the parameters that are not standard to the RMQ client (but used by NServiceBus) via code, using configuration API. Documentation will be updated accordingly.

Thank you for your patience.
