### ISSUE TITLE
Support custom delayed delivery

### ISSUE THREAD

**Issue by nirpet** [Particular/NServiceBus.RabbitMQ#579]
Hi,

The delay delivery infrastructure (Dead letter exchanges + TTL) does not meet our disaster recovery constraints. We can't use dead letter exchanges + TTL so we have created a service that persists the messages in a different database and publishes them to a configured exchange with a configured routing key at the desired time. 

Is implementing a feature that allows the use of custom delay delivery infrastructure possible? 
If so, does the use of a customize delayed delivery infrastructure affect the monitoring features?

**Comment by SzymonPobiega** [comment]
Hi @nirpet 

So you have built your delay service by replacing the behavior of the built-in delay exchanges and binding a single queue to all of them?

The monitoring does not make any assumptions on the way messages are delayed so it should work as expected. Do you experience any problems?

**Comment by nirpet** [comment]
We are not using nservicebus yet so I didn't expreience any problems yet.
We are considering the use of Nservicebus sagas for a specific case and we are already using rabbitmq so we thought that using the RabbitMqTransport is best suited for us. 
The problem is that we can't use this transport if it does not meet our DR constraints as I mentioned earlier.

Our delay service saves the delayed messages data outside RabbitMq in a database that is replicated to our passive site so we are able to recover from disaters easily. There is a pooling loop that publishes the message when the delay expires. It is actually quite similar to how you implemented delay delivery in your SqlServer implementation: https://github.com/Particular/NServiceBus.SqlServer/blob/master/src/NServiceBus.Transport.SqlServer/DelayedDelivery/DueDelayedMessageProcessor.cs

If the Infrastructure allowed to implement and configure a custom DelayInfrastructre it would have solved our DR problems.
@SzymonPobiega are you interested in a pull request?

**Comment by SzymonPobiega** [comment]
@nirpet We plan to move in future towards a solution where the Saga components stores the timeouts in the saga store and the transport delayed infrastructure is only used as a helper for triggering these timeouts. But we don't have any ETA for that.

Can I ask why is the current solution not compatible with your DR? I guess you replicated the messages in the "regular" queues to the DR site so I wonder if the same strategy can be used for the delay queue messages?

Last but not least, if you are interested in the Saga side of NServiceBus an option might be to run an SQL transport + SQL persistence endpoint to host sagas and integrate it via NServiceBus.Router with your Rabbit infrastructure. This way the timeouts will be stored in the SQL Server instance and it will be easy to migrate them to the DR site.

**Comment by nirpet** [comment]
Thanks @SzymonPobiega

Regarding the DR issue, we save replications of the data on our passive site with a configured TTL. Messages that stay in a queue longer than that will be deleted. We can't change this behavior currently so we will not be able to use the RabbitMqTransport.

SQLServerTransport is an option but we are expecting high throughput (above 500 messages/s) in the future so we thought that RabbitMq will preform better.

**Comment by SzymonPobiega** [comment]
SQL Server Transport should be totally fine for 500-1000 messages/s in a single endpoint but there another option.

That option would be to [extend the pipeline](https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors) with a behavior like [this one](RouteDeferredMessageToTimeoutManagerBehavior). In the behavior you would replace the existing routing strategies with a custom one that
 - adds headers that inform where and when the message should be delivered
 - sets the destination to your existing delayed delivery service

By doing this you would bypass the default RabbitMQ transport delayed delivery handling because after your behavior the message would no longer be considered a delayed one (the behavior removes the delay *constraint*).

**Comment by nirpet** [comment]
That sounds great! thanks a lot for all your help @SzymonPobiega
