### ISSUE TITLE
NServiceBus.RabbitMQ does not support RabbitMQ.Client 6.0

### ISSUE THREAD

**Issue by HermannGruber** [Particular/NServiceBus.RabbitMQ#627]
Recently our team ran into a problem with RabbitMQ.Client 5.2, and we solved temporarily it with a [workaround](https://stackoverflow.com/a/59981777/2792414). The RabbitMQ.Client team fixed the problem, and released a new major version, namely 6.0. But the latest version of NServiceBus.RabbitMQ is not compatible with that version. What are the plans for a release of your product that supports the new major version of RabbitMQ.Client?

**Comment by ramonsmits** [comment]
@HermannGruber We just released a version targeting 5.2

Version 6.0 was release 6 days ago and introduced some breaking changes which need to be addressed.

**Comment by HermannGruber** [comment]
@ramonsmits thank you for your quick answer! Of course, this takes time - it would be very kind if you drop a line here once the plans for supporting the 6.0 version become more concrete, if this fits with your process.

**Comment by HermannGruber** [comment]
More than a month has passed since my initial inquiry. Are the breaking changes introduced with 6.0 difficult to address? Or is the issue I opened more of a low prio thing? I don't want to be pushy - it simply would be interesting for my team to have a rough estimate.

**Comment by sungam3r** [comment]
Also need support for RabbitMQ.Client 6.0

**Comment by sungam3r** [comment]
EasyNetQ [supports](https://github.com/EasyNetQ/EasyNetQ/releases/tag/4.0.0) RabbitMQ.Client 6.0 since version 4.0.0. Now it is impossible to use EasyNetQ >= 4.0.0 and NServiceBus.RabbitMQ in one application.

**Comment by dvdstelt** [comment]
This issue has now been prioritized and will be picked up. We are working on several other things (not RabbitMQ related) as well, so it might take a couple of weeks before a new release appears.

**Comment by ramonsmits** [comment]
Development of supporting RabbitMQ.Client 6.1 has started. This will be a breaking change and be part of 6.0.0.

**Comment by HermannGruber** [comment]
Is there already an estimate when 6.0.0 will be released? Previous releases were as follows:

5.0.0 May 2018
4.0.0 Oct 2016
3.0.0 Jun 2015

Extrapolating from that, I would have expected the next major release around late 2019 :-) But, I guess the cadence slows down as the product matures?

**Comment by dvdstelt** [comment]
We're working on some other stuff as well, but the new client library has already been included.
https://github.com/Particular/NServiceBus.RabbitMQ/pull/639

After the other work, we'll release it. Probably a matter of weeks at most. Likely sooner.

**Comment by HermannGruber** [comment]
This is really great! Thanks a lot, both for your effort and for the feedback.

**Comment by bording** [comment]
NServiceBus.RabbitMQ 6.0.0 has been released, and it works with RabbitMQ.Client 6.1.0.
