### ISSUE TITLE
Allow to create connection using RabbitMq IConnection CreateConnection(IList<string> hostnames) overload

### ISSUE THREAD

**Issue by alexander-kucherov** [Particular/NServiceBus.RabbitMQ#707]
We use 3 nodes rabbitmq cluster. 
How can I configure my NSB worker service for round robin connect to nodes?
With native RabbitMQ.Client I can do it using LocalEndpoints and DefaultEndpointResolver.
NServiceBus.Transport.RabbitMQ encapsulates connection creation in internal ConnectionFactory class without providing any extension points.

**Comment by danielmarbach** [comment]
@alexander-kucherov 

Thanks for raising this. We have already an issue that tracks this feature

https://github.com/Particular/NServiceBus.RabbitMQ/issues/525

We had support for this in v3 of the transport but removed it, see the justification on that issue

https://github.com/Particular/NServiceBus.RabbitMQ/issues/525#issuecomment-468753699

In theory that is something, we might be able to reintroduce. Please chime in on the other issue is possible (upvoting, make a comment or tell us more about your use cases).

I'm closing this one as a duplicate.
