### ISSUE TITLE
Multiple Subscribers w/ Same Endpoint Name Don't All Receive Messages

### ISSUE THREAD

**Issue by burkhartt** [Particular/NServiceBus.RabbitMQ#72]
See https://groups.google.com/forum/#!topic/particularsoftware/42FQlZcA7fY

We have an issue where we have a WebAPI server, but it is load balanced. When another process publishes an event, we want *both* WebAPI servers to receive the message; however, the way that NServiceBus has configured the queues/exchanges, it appears to not support this. Is this true? Both WebAPI servers have the same EndpointName() defined (as "WebService")

So if I go into RabbitMQ Management UI, it shows that there is an exchange of "WebService" and that it binds to a queue named "WebService" and within that queue, it has 2 consumers (both of our WebAPI machines). However, according to http://stackoverflow.com/questions/10620976/rabbitmq-amqp-single-queue-multiple-consumers-for-same-message this yields a round-robin message handling. The messages that are received in the queue will *not* be picked up by both handlers.

So my question is... how do we deal w/ the situation laid out? I think what we really want is for the queue name to be configurable as well as the exchange. We want both WebAPIs to be part of the same exchange, but have different queue names.

---

Thought I had this solved with 

configuration.ScaleOut().UseUniqueBrokerQueuePerMachine();

However, that still doesn't work. The RabbitMQ topology looks like:

--Exchanges--
WebService
WebService.Machine1
WebService.Machine2

--Queues bound to exchange WebService--
WebService

--Queues bound to exchange WebService.Machine1--
WebService.Machine1

--Queues bound to exchange WebService.Machine2--
WebService.Machine2

--Consumers for queue WebService--
IP for machine 1
IP for machine 2

--Consumers for queue WebService.Machine1--
IP for machine 1

--Consumers for queue WebService.Machine2--
IP for machine 2

When I do a publish, it still appears to be routed to the WebService exchange, which goes to the WebService queue, which does the round-robin handling and only goes to one of the machines, but I need it to go to both. Shouldn't it change the configuration on RabbitMQ to fan out the published messages to all of the machines that are subscribing? It doesn't appear to do this by default?

**Comment by burkhartt** [comment]
If I go into the RabbitMQ Web UI and manually bind queue "WebService.Machine2" to exchange "WebService" and publish, then both machines receive the message. I think this should be what NServiceBus does for you right?

**Comment by burkhartt** [comment]
For additional information about what I'm talking about, visit http://jmcle.github.io/rabbitmq-visualizer/ and click on the "Import" button and paste in the following JSON:

{
  "exchanges": [
    {
      "name": "Engine.Messages.Inventory:InventoryUpdatedEvent",
      "type": "1",
      "x": 312,
      "y": 237,
      "resource_type": "exchange",
      "id": 1
    },
    {
      "name": "WebService",
      "resource_type": "exchange",
      "id": 34,
      "type": "1",
      "x": 559,
      "y": 231
    },
    {
      "name": "WebService.USAM-GATQAWEB1",
      "resource_type": "exchange",
      "id": 37,
      "type": "1",
      "x": 554,
      "y": 372
    },
    {
      "name": "WebService.USB-PCTBSTIMB",
      "resource_type": "exchange",
      "id": 38,
      "type": "1",
      "x": 553,
      "y": 506
    }
  ],
  "queues": [
    {
      "name": "WebService",
      "resource_type": "queue",
      "id": 39,
      "type": 0,
      "x": 762,
      "y": 230,
      "messages": [],
      "totalConsumers": 2,
      "lastConsumer": 0
    },
    {
      "name": "WebService.USAM-GATQAWEB1",
      "resource_type": "queue",
      "id": 50,
      "type": 0,
      "x": 762,
      "y": 371,
      "messages": [],
      "totalConsumers": 1,
      "lastConsumer": 0
    },
    {
      "name": "WebService.USB-PCTBSTIMB",
      "resource_type": "queue",
      "id": 54,
      "type": 0,
      "x": 768,
      "y": 505,
      "messages": []
    }
  ],
  "bindings": [
    {
      "source": 8,
      "vhost": "default",
      "source_type": "producer",
      "destination": 1,
      "destination_type": "exchange",
      "id": 16,
      "routing_key": "di.usr.one",
      "arguments": []
    },
    {
      "source": 1,
      "vhost": "demo",
      "destination": 1,
      "destination_type": "exchange",
      "routing_key": "key",
      "arguments": [],
      "id": 35,
      "source_type": "exchange"
    },
    {
      "source": 34,
      "vhost": "demo",
      "destination": 39,
      "destination_type": "queue",
      "routing_key": "key",
      "arguments": [],
      "id": 40,
      "source_type": "exchange"
    },
    {
      "source": 39,
      "vhost": "demo",
      "destination": 41,
      "destination_type": "consumer",
      "routing_key": "key",
      "arguments": [],
      "id": 43,
      "source_type": "queue"
    },
    {
      "source": 39,
      "vhost": "demo",
      "destination": 42,
      "destination_type": "consumer",
      "routing_key": "key",
      "arguments": [],
      "id": 44,
      "source_type": "queue"
    },
    {
      "source": 1,
      "vhost": "demo",
      "destination": 34,
      "destination_type": "exchange",
      "routing_key": "key",
      "arguments": [],
      "id": 46,
      "source_type": "exchange"
    },
    {
      "source": 37,
      "vhost": "demo",
      "destination": 50,
      "destination_type": "queue",
      "routing_key": "key",
      "arguments": [],
      "id": 51,
      "source_type": "exchange"
    },
    {
      "source": 50,
      "vhost": "demo",
      "destination": 41,
      "destination_type": "consumer",
      "routing_key": "key",
      "arguments": [],
      "id": 52,
      "source_type": "queue"
    },
    {
      "source": 38,
      "vhost": "demo",
      "destination": 54,
      "destination_type": "queue",
      "routing_key": "key",
      "arguments": [],
      "id": 55,
      "source_type": "exchange"
    },
    {
      "source": 54,
      "vhost": "demo",
      "destination": 42,
      "destination_type": "consumer",
      "routing_key": "key",
      "arguments": [],
      "id": 56,
      "source_type": "queue"
    }
  ],
  "producers": [
    {
      "name": "GAT.Cloud.PhoenixDepartures",
      "x": 107,
      "y": 184,
      "interval": 5,
      "publish": {
        "to": 1,
        "payload": "one",
        "routing_key": "di.usr.one"
      },
      "resource_type": "producer",
      "id": 8
    }
  ],
  "consumers": [
    {
      "name": "QA",
      "resource_type": "consumer",
      "id": 41,
      "type": 0,
      "x": 1054,
      "y": 228
    },
    {
      "name": "Localhost",
      "resource_type": "consumer",
      "id": 42,
      "type": 0,
      "x": 1050,
      "y": 504
    }
  ]
}


Then press shift + click on the green circle. You'll notice that it does round robin messaging. Whatever the default NServiceBus + RabbitMQ topology is, shouldn't it take into account that a publish should really make it to both consumers 100% of the time?

**Comment by andreasohlund** [comment]
What version of NServiceBus.RabbitMQ is this? 

Since we handle callbacks more explicit now the `UseSingleBrokerQueue` setting is a no-op since it was only introduced to make callbacks work when scaled out. In this case what you need is to make the web endpoints unique so that each one of them gets the message. You can do this by adding the machine name to the endpoint name using:

[`config.EndpointName("MyEndpoint" + Environment.MachineName)`](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/BusConfiguration.cs#L104)

Does this make sense?

**Comment by burkhartt** [comment]
We are on the latest version of rabbitmq. That was actually the route that I took in the end and it works. The only thing is that if I do that then it sort of makes a "send" a little strange because in the message routing you would have to know the machine name as well. Perhaps that is not a big deal. I just wasn't certain that that was the proper solution. But if you recommend it then I will go with it :-)

**Comment by andreasohlund** [comment]
Another option would be to have the web servers share the storage (eg. distributed cache). That way all instance will have the same data regardless of which one gets the message.
