### ISSUE TITLE
Pass correct NServiceBus version in connection info

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#75]
Today we pass the asmversion

https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/Config/ConnectionConfiguration.cs#L57

should be the FileVersion

**Comment by bording** [comment]
This has been added to the 4.0 release. It now shows the FileVersion for both NServiceBus and the Transport.

**Comment by andreasohlund** [comment]
So assign to the v4 milestone and close?
