### ISSUE TITLE
Some tests targeting .NET Core 3.x fail when run against Amazon MQ service broker

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.RabbitMQ#751]
Running the tests suite against the Amazon MQ service broker causes some (11 all my attempts) tests to fail. Tests targeting the .NET Framework are all green. Only some of the tests targeting .NET Core 3.x are failing. The two more frequent reasons for failure are:

- "No handlers could be found for message type: <insert base class here>" which seems to point to something that is off whit inheritance support
- "An error occurred while attempting to extract logical messages from incoming physical message"

Once this issue and https://github.com/Particular/NServiceBus.RabbitMQ/issues/750 have been completed, the entire test suite should be re-run against an ActiveMQ instance to validate support.

**Comment by WilliamBZA** [comment]
Tests now pass after #799
