### ISSUE TITLE
Version 2.0.X churns CPU when the broker connection is lost

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#77]
This seems to be fixed on v2.1. Since the endpoint doesn't recover I propose that we backport the fix to a 2.0.5 release

### Repro

* Create a simple endpoint 

```
 var c = new BusConfiguration();

            c.UseTransport<RabbitMQTransport>();
            c.UsePersistence<InMemoryPersistence>();

            var bus = Bus.Create(c);

            bus.Start();

            Console.ReadKey();
```

* Run it
* Restart the broker: `Restart-Service RabbitMQ`

**Comment by andreasohlund** [comment]
@johnsimons thoughts?

**Comment by bording** [comment]
@andreasohlund Given that 3.1.0 is the latest production release and we're working on 4.0, do you still think this needs to be backported?
