### ISSUE TITLE
Validate the circuit breaker settings

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#78]
To better protect users from configuring the circuitbreaker with threshold that will cause outages we should validate that:

`TimeToWaitAfterFailure` is max `TimeToWaitBeforeTriggering`/2

This check would have prevented https://github.com/Particular/NServiceBus.RabbitMQ/issues/76

**Comment by bording** [comment]
@andreasohlund Is this something you think should still go into a 3.x release?

For 4.0, the circuitbreaker settings have changed. `TimeToWaitBeforeTriggering` is the only setting to configure for it, and it triggers if the message pump detects that the connection to the broker has been lost.

Based on that, the value to validate against would be the connection retry `RetryDelay` that gets passed in via the connection string. Given that `RetryDelay` is measured in seconds and the circuitbreaker's default `TimeToWaitBeforeTriggering` is set to 2 minutes, these feel different enough that it doesn't seem likely that someone would configure a `RetryDelay` that was larger than `TimeToWaitBeforeTriggering`

Thoughts?
