### ISSUE TITLE
NServiceBus.RabbitMQ V 2.1.1-beta (likely V 2.1.1 as well) establishes two connections.

### ISSUE THREAD

**Issue by GopiKand** [Particular/NServiceBus.RabbitMQ#81]
In a RabbitMQ clustered environment the RabbitMQ transport establishes two connections to a new node on a current node failure. One of the connections have no associated channels while the other looks right.

**Comment by andreasohlund** [comment]
Can you double check the connection details? Are but marked as "Consume"?

**Comment by GopiKand** [comment]
In fact one marked "publish" and the other "consume".

**Comment by andreasohlund** [comment]
Ok, that would be expected if your endpoint is send/publishing messages. We
open a connection and keep it open for that specific purpose.

So I'm not sure if this is an issue?

**Comment by GopiKand** [comment]
Sounds good to me. On further testing all seems to work fine.

**Comment by andreasohlund** [comment]
Awesome. We'll proceed with the release of 2.1.2 then. Thanks for all your
help its been invaluable!
