### ISSUE TITLE
Add "scheme=amqps" configuration option (and code to support TLS/AMQPS) to RabbitMQ transport connection string

### ISSUE THREAD

**Issue by oshea00** [Particular/NServiceBus.RabbitMQ#82]

**Comment by andreasohlund** [comment]
Seems what's needed here is to modify the connection string parser to support

cacertfile
certfile
keyfile
verify
fail_if_no_peer_cert

https://www.rabbitmq.com/uri-query-parameters.html

**Comment by SimonCropp** [comment]
@andreasohlund r u working on this?

**Comment by andreasohlund** [comment]
I was planning to try to get a pull going. Want to take a stab at it?

**Comment by bording** [comment]
This has been added with 0146f3911c61040aec031a00ff223f1122ad67a5 and will be included as part of the 4.0 release.

**Comment by johnsimons** [comment]
@oshea00 quick question regarding your request to support TLS/AMQPS, are you planning to configure RabbitMQ broker to require TLS connections and to reject non-secure connections ?

**Comment by adamralph** [comment]
Backported to 3.x in https://github.com/Particular/NServiceBus.RabbitMQ/pull/147
