### ISSUE TITLE
Only log a warning when the broker connection is lost and we're trying to reconnect

### ISSUE THREAD

**Issue by Loupi** [Particular/NServiceBus.RabbitMQ#86]
Using NServiceBug.RabbitMQ 2.1.2

Logger: NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy

These exceptions appear in batches, on the same minute a few times a day
There is one or more of those exceptions per exchange. (around 60)
This does not seem to affect performances, and no message is lost int the end.

System.AggregateException: One or more errors occurred. ---> System.IO.EndOfStreamException: SharedQueue closed     
at RabbitMQ.Util.SharedQueue`1.Dequeue(Int32 millisecondsTimeout, T& result)     
at NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy.DequeueMessage(QueueingBasicConsumer consumer, Int32 dequeueTimeout) 
in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqDequeueStrategy.cs:line 257     
at NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy.ConsumeMessages(Object state) 
in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqDequeueStrategy.cs:line 247     
at System.Threading.Tasks.Task.Execute()     
--- End of inner exception stack trace ---

**Comment by andreasohlund** [comment]
Since we're running with X threads I would expect there to be a "batch" of exceptions logged if the connection goes down?

Could it be something flaky in the broker? Anything logged on the broker side?

Given that we manage to reconnect and recover what would you propose we do? (dial down the log levels?)

**Comment by Loupi** [comment]
Dialing down the log levels for this case looks like a good solution. Setting the level to warning would do the job (I think).

The broker looks fine, but I will perform a deeper investigation on that side. The timeout channels are also producing the error.

Failed to receive messages from DataLogger
Failed to receive messages from DataLogger.TimeoutsDispatcher
Failed to receive messages from DataLogger.Timeouts

**Comment by andreasohlund** [comment]
Yes the satellites you mention also have a separate channel open and since they also fails at the same time I would suspect the broker forcing all connections to close for some reason?

**Comment by andreasohlund** [comment]
Title updated to reflect the proposed change

**Comment by bording** [comment]
@andreasohlund For the 4.0 release, I've moved to using the built-in RabbitMQ client connection recovery mechanism, so we no longer have these log messages around connection recovery.

However, the message pump circuitbreaker now arms when a connection is lost, so you will still see log entries corresponding to connection failure and restoration.

Currently, the circuitbreaker uses the following log levels:

Success: Info
Failure: Warn
Trigger: Warn

Should I update Success to also use Warn instead?

**Comment by bording** [comment]
Given that the "SharedQueue closed" error shouldn't happen in the 4.0 transport and the way that connection recovery is now handled, it seems like making any additional changes related to this is unnecessary at this point.
