### ISSUE TITLE
Revise multi-host connection string support and simplify extensibility points

### ISSUE THREAD

**Issue by j--wong** [Particular/NServiceBus.RabbitMQ#89]
This is more of an improvement proposal / topic for discussion.  The recommended approach for deploying a Rabbit cluster is behind a load balancer (ref: https://www.rabbitmq.com/clustering.html). So instead of NServiceBus transport managing connections to individual nodes, it should encourage the best practice set up of going through a load balancer.  

The benefit of removing the load balancing concerns out of the transport will not only simplify the configuration, it will allow us to add/remove nodes in the cluster without having to change transport configuration. Also in situation of taking a bad node out of the cluster would be best done in the load balancer than in the .NET config and then stop/start the service. Transport config will be decoupled from the cluster config.

Another observation is that the underlying RabbitMQ .NET client lib has an implementation of `IConnection` that automatically reconnects in case of dropping connections in `AutorecoveringConnection` class which I think will simplify `PersistentConnection` implementation and may remove the need for `ClusterAwareConnectionFactory`.  As a result, underlying `ConnectionFactory` can be used directly where SSL/TLS related connection options can be set up more easily which is the reason why I am looking at extending the transport.

While `IManageRabbitMqConnections` provides an extensibility point for returning custom `IConnection` objects, implementing that interface is not straightforward even though the interface definition is very simple.  I think that's partly due to `PersistentConnection` and `ClusterAware*` implementations.  Overall, simpler extensibility points will help us extend/add features to the transport more easily.

**Comment by andreasohlund** [comment]
Nice timing, we've had other issues with the "failover" feature so we've decided to deprecate it cc @janovesk 

Good catch with the autorecovery , we should definitely try to use it instead so that we can remove all that extra code.

In short: big +1 from me!

**Comment by janovesk** [comment]
Valid points you bring up here @j--wong. We are deprecating this feature and I want to make sure we provide you with extension points you can use.

Can you expand on what you would like to see as an extensibility point?

**Comment by andreasohlund** [comment]
@j--wong have you seen this one http://insidethecpu.com/2014/11/17/load-balancing-a-rabbitmq-cluster/

not very optimal to use a loadbalancer but I guess that the best guidance we can give?

**Comment by j--wong** [comment]
@andreasohlund Interesting article!  I've been experimenting with Rabbit clustering and HA for almost 6 months now.  Our goal is to achieve data consistency and no data loss above everything else (out of CAP Theorem).  

During the experiment I found that connecting clients to individual node is a bad idea and can/will incur data loss (very dangerous thing to do!) **when** network partition occurs. To expand a bit on this, let's say, 
* we have a 3-node rabbit cluster (rabbit1, rabbit2 and rabbit3) 
* we have a mirrored queue called 'test-queue' created on rabbit1 hence the master (data replicated across all other nodes in the cluster)
* in a normal failure mode, let's say rabbit1 goes down, rabbit2 or rabbit3 will take over as master and everyone's happy
* but during a network partition, let's say, rabbit1 + rabbit2 on one side of the partition and rabbit3 on another
* because rabbit3 no longer sees the other nodes in the cluster, it will promote itself as the master and on the other side of the partition rabbit1 is still the master
* now we have two sides of the partition evolving independently and mirrored queues can no longer able to sync across all nodes
* and a client continue publishing to rabbit3 directly and another one to rabbit1 and we will introduce data *inconsistency* within the cluster
* when the time comes to recover network partition, Rabbit will force you to pick one side of the partition as most consistent one; if you pick rabbit1+2 then messages published directly to rabbit3 will be lost and if you pick rabbit3, data on rabbit1+2 will be lost
* Rabbit has built-in config to handle network partition a bit better so what we plan on doing is to set `cluster_partition_handling` setting to `pause_minority`
* with that config, rabbit3 will be suspended as it is the minority
* the benefit of using a load balancer is that when a node is suspended (hence amqp/amqps ports stop listening), it will be automatically taken out of the pool
* Reference and a bit more info here: https://www.rabbitmq.com/partitions.html

So in summary, yes going through a load balancer will create that extra hop but that's how it was designed and so far we've been testing with various payload sizes and we didn't see any significant performance degradation going through a load balancer.

We also did research around how Rabbit large-scale, highly-available deployments are done involving hundreds of nodes in a cluster and we have seen load balancers being used in all deployments.  For example, http://blog.pivotal.io/pivotal/products/rabbitmq-hits-one-million-messages-per-second-on-google-compute-engine

NServiceBus promise of no data loss was very appealing to us; that's one of the top reasons why we are adopting it as our messaging library.  After using it for a while, we realised that to achieve no data loss, the answer lies in the underlying transport configuration and associated persistence and replication options and more on the infrastructure side (like SAN replication, etc).  So we picked our transport (Rabbit) and we invested quite a bit of time in getting its configuration right.

**Comment by andreasohlund** [comment]
Thanks for the awesome writeup Josh. Much of what you say is in line with:

https://aphyr.com/posts/315-call-me-maybe-rabbitmq

Are you saying that pause minority will help with the splitbrain issue mentioned?

**Comment by SzymonPobiega** [comment]
Split out into
 * SSL #90 
 * IManage... extension point #88 
 * Remove multi-broker #91
