### ISSUE TITLE
Remove the multi broker anti-feature

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#96]

**Comment by adamralph** [comment]
Closed by https://github.com/Particular/NServiceBus.RabbitMQ/pull/91

**Comment by burkhartt** [comment]
What is the reason for this feature to be removed?

**Comment by adamralph** [comment]
For more detail about this change, see the [announcement](https://groups.google.com/d/topic/particularsoftware/8EkMRN97hVU/discussion) and the related [documentation](http://docs.particular.net/nservicebus/rabbitmq/cluster).
