### ISSUE TITLE
NServiceBus fails in a RabbitMQ federated scenario

### ISSUE THREAD

**Issue by GopiKand** [Particular/NServiceBus.RabbitMQ#98]
RabbitMQ uses a header field (x-received-from) to identify messages routed by the federation plugin from one node to the other. This field will carry the source node uri in it. In some special cases NServiceBus uses the source message header data on subsequent messages it generates leading to this header field getting copied over. If this message needs to be federated from one node to the other the RabbitMQ federation module breaks for that specific queue never to be re-established until the message itself is deleted.

The fix to it is to blindly remove the "x-received-from" header entry in the NServiceBus RabbitMQ transport method RabbitMqTransportMessageExtensions.FillRabbitMqProperties method.

Appreciate if we could have this done as part of the 2.1.3 branch

![image](https://cloud.githubusercontent.com/assets/7553914/8860148/899af95a-3147-11e5-87d3-5f2172251d3e.png)

**Comment by mauroservienti** [comment]
As a workaround you can use a [message mutator](http://docs.particular.net/nservicebus/pipeline/message-mutators) to remove from the the incoming `transport message` the `x-received-from` header.

**Comment by bording** [comment]
@mauroservienti Do you know what scenarios we'd reuse the headers like that, and does it still happen in v6?

**Comment by mauroservienti** [comment]
Sincerely don't know. The only things that comes to my mind are `error`, `audit` Qs and SLRs that go through the `timeout manager` or in case of `bus.Defer` and message forwarding.

**Comment by GopiKand** [comment]
As a side note if it matters at all, the newer version of RabbitMQ v3.5+ has a fix for this issue. Did some smoke test while ago of this fix and have not seen this issue show up.

**Comment by bording** [comment]
@GopiKand That's good to hear! 

Since it sounds like the underlying issue you were encountering has been fixed by RabbitMQ itself, do you still see a need for us to do anything at the transport level?

If not, I'd like to go ahead and close this issue and consider it resolved.

**Comment by GopiKand** [comment]
Nope. Please go ahead close and mark it as resolved.
