### ISSUE TITLE
Long Dequeue timeouts can prevent an Endpoint from shutting down

### ISSUE THREAD

**Issue by kevin-whalley-gc** [Particular/NServiceBus.RabbitMQ#99]
I think on a practical level the a timeout should be used when the transport is stopping. 

Ran into a situation today where I'd let a local dev DeQueueTimeout of 5 minutes through to a shared dev server. This has the effect of preventing the endpoint from ever being able to shutdown within the 120 seconds Windows uses by default for stopping a Windows Service. As currently written the DequeueStrategy will issue a cancellation to a thread that may be waiting for a long timeout, and the cancellation will never be processed in time because it will only be processed on the next 'Consume'. This presents as a service that is 'stopping' permanently.

https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/RabbitMqDequeueStrategy.cs#L107

**Comment by andreasohlund** [comment]
Makes sense, could put a timelimit on the wait.

@johnsimons do you have other ideas?

**Comment by bording** [comment]
This behavior will no longer be seen in the 4.0 release because the message pump no longer uses a dequeue timeout.

I'm going to close this as fixed in 4.0.
